import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {migrateNarrationProbe,seedNarrationFixture} from '../scripts/narration-fixtures';
import {admitGeneration,findGeneration,failGeneration,generationView,listGenerations,generationRights} from '../packages/db/src/index';
import {generationVideo} from '../apps/web/lib/generations';
import {videoReport,videoFixture} from '../fixtures/video';

test('admission D1 atomique : idempotence, budget, isolation, quota et résultat tardif',async t=>{
  const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("fixture")}}',compatibilityDate:'2026-09-27',d1Databases:['DB'],r2Buckets:['MEDIA']}));t.after(()=>mf.dispose());
  const env=await mf.getBindings<{DB:D1Database;MEDIA:R2Bucket}>();await migrateNarrationProbe(env.DB);
  const {agencyId,jobId}=await seedNarrationFixture(env.DB,'admission',true);
  await env.DB.prepare("UPDATE jobs SET status='failed',error_code='FIXTURE',lease_until=NULL WHERE id=?").bind(jobId).run();
  const now=new Date().toISOString();await env.DB.prepare('INSERT INTO hosted_import_budget(month,baseline_cents,ceiling_cents,paused) VALUES(?,0,3500,0)').bind(now.slice(0,7)).run();
  await env.DB.exec("UPDATE generation_control SET enabled=1");
  await env.DB.prepare('INSERT INTO generation_access(agency_id,allocation_id,enabled) VALUES(?,?,1)').bind(agencyId,'allocation-admission').run();
  await env.DB.prepare('INSERT INTO import_usage(day,attempts) VALUES(?,10) ON CONFLICT(day) DO UPDATE SET attempts=10').bind(now.slice(0,10)).run();
  await assert.rejects(admitGeneration(env.DB,agencyId,'import-full-before-cost',{url:'https://agence.example/annonce/1'},'true'),/IMPORT_LIMIT/);
  assert.equal((await env.DB.prepare('SELECT baseline_cents AS n FROM hosted_import_budget').first<{n:number}>())!.n,0);
  assert.ok((await generationRights(env.DB,agencyId,'true')).importRetryAt);
  await env.DB.prepare('UPDATE import_usage SET attempts=1 WHERE day=?').bind(now.slice(0,10)).run();
  const body={listingId:'listing-admission'},key='same-admission-key-123456';
  const [a,b]=await Promise.all([1,2].map(()=>admitGeneration(env.DB,agencyId,key,body,'true')));
  assert.equal(a.jobId,b.jobId);assert.equal(a.status,'queued');assert.equal(a.workflowId,`generation-${a.jobId}`);
  assert.equal((await env.DB.prepare('SELECT reserved FROM allocations WHERE agency_id=?').bind(agencyId).first<{reserved:number}>())!.reserved,1);
  assert.equal((await env.DB.prepare('SELECT baseline_cents AS n FROM hosted_import_budget').first<{n:number}>())!.n,120);
  assert.equal((await env.DB.prepare('SELECT count(*) AS n FROM job_launch_intents').first<{n:number}>())!.n,1);
  await assert.rejects(admitGeneration(env.DB,agencyId,key,{url:'https://agence.example/annonce/1'},'true'),/CONFLICT/);
  await assert.rejects(admitGeneration(env.DB,agencyId,'another-key-12345678',body,'true'),/QUOTA_EXHAUSTED/);
  await assert.rejects(admitGeneration(env.DB,agencyId,'spoofing-1234567890',{...body,agencyId:'another'},'true'),/VALIDATION_ERROR/);
  assert.equal(await findGeneration(env.DB,'another-agency',a.jobId),null);
  assert.deepEqual((await listGenerations(env.DB,'another-agency')).jobs,[]);
  assert.equal((await listGenerations(env.DB,agencyId)).jobs.length,1);
  const initial=await findGeneration(env.DB,agencyId,a.jobId);assert.equal(generationView(initial!).videoUrl,null);
  await env.DB.exec('UPDATE generation_control SET enabled=0');
  assert.equal((await admitGeneration(env.DB,agencyId,key,body,'false')).jobId,a.jobId);
  assert.equal((await generationRights(env.DB,agencyId,'true')).generationEnabled,false);
  await assert.rejects(admitGeneration(env.DB,agencyId,'new-paused-12345678',body,'true'),/GENERATIONS_PAUSED/);
  await failGeneration(env.DB,a,'GENERATION_TIMEOUT');await failGeneration(env.DB,a,'GENERATION_FAILED');
  const quota=await env.DB.prepare('SELECT reserved,consumed FROM allocations WHERE agency_id=?').bind(agencyId).first();assert.deepEqual(quota,{reserved:0,consumed:0});
  await assert.rejects(env.DB.prepare("UPDATE jobs SET status='ready',error_code=NULL WHERE id=?").bind(a.jobId).run(),/GENERATION_TERMINAL/);
  await assert.rejects(generationVideo(new Request('https://test/video'),env,agencyId,a.jobId),/NOT_FOUND/);
  assert.equal((await env.DB.prepare('SELECT baseline_cents AS n FROM hosted_import_budget').first<{n:number}>())!.n,120);
  await env.DB.exec('UPDATE generation_control SET enabled=1');
  const ready=await admitGeneration(env.DB,agencyId,'ready-video-12345678',body,'true');
  await assert.rejects(env.DB.prepare("UPDATE jobs SET status='ready',lease_until=NULL WHERE id=?").bind(ready.jobId).run(),/GENERATION_ARTIFACT_REQUIRED/);
  const f=await videoFixture(),bytes=new Uint8Array([1,2,3,4,5,6]),report=videoReport('a'.repeat(64),f.manifest,bytes);
  const objectKey=`agencies/${agencyId}/jobs/${ready.jobId}/video/output.mp4`;
  await env.MEDIA.put(objectKey,bytes,{customMetadata:{sha256:report.sha256}});
  await env.DB.batch([env.DB.prepare('INSERT INTO generation_artifacts VALUES(?,?,?,?)').bind(ready.jobId,objectKey,JSON.stringify(report),now),
    env.DB.prepare("UPDATE jobs SET status='ready',lease_until=NULL WHERE id=?").bind(ready.jobId)]);
  assert.deepEqual(await env.DB.prepare('SELECT reserved,consumed FROM allocations WHERE agency_id=?').bind(agencyId).first(),{reserved:0,consumed:1});
  await env.DB.exec('UPDATE generation_control SET enabled=0');
  const file=await generationVideo(new Request('https://test/video',{headers:{Range:'bytes=1-3'}}),env,agencyId,ready.jobId);
  assert.equal(file.status,206);assert.equal(file.headers.get('Content-Range'),'bytes 1-3/6');assert.deepEqual([...new Uint8Array(await file.arrayBuffer())],[2,3,4]);
  assert.equal((await generationVideo(new Request('https://test/video',{headers:{Range:'bytes=80-100'}}),env,agencyId,ready.jobId)).status,416);
  const download=await generationVideo(new Request('https://test/video?download=1'),env,agencyId,ready.jobId);assert.deepEqual([...new Uint8Array(await download.arrayBuffer())],[1,2,3,4,5,6]);
  await assert.rejects(generationVideo(new Request('https://test/video'),env,'another-agency',ready.jobId),/NOT_FOUND/);
});
