import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {videoFixture,videoReport} from '../fixtures/video';
import {videoManifestHash,videoAssets,videoPreviewKey} from '../packages/contracts/src/index';
import type {VideoJob} from '../apps/pipeline/src/video-coordinator';
type Snapshot={starts:number;cleaned:boolean;stopped:boolean;job:VideoJob;state:{active:string|null;budget:{attempts:number;committedCents:number}}};
test('contrôleur durable workerd : budget, concurrence, R2, timeout et coupures',async t=>{
  const directory=await mkdtemp(path.join(tmpdir(),'bienvu-video-do-'));t.after(()=>rm(directory,{recursive:true,force:true}));
  const require=createRequire(import.meta.url),wrangler=createRequire(require.resolve('wrangler/package.json'));
  const esbuild=await import(pathToFileURL(wrangler.resolve('esbuild')).href) as {build:(o:unknown)=>Promise<unknown>};
  const scriptPath=path.join(directory,'worker.mjs');
  await esbuild.build({entryPoints:['fixtures/video-worker.ts'],outfile:scriptPath,bundle:true,platform:'neutral',format:'esm',target:'es2022',external:['cloudflare:*','node:*'],conditions:['workerd','worker','browser']});
  const options={...convertV4MiniflareOptions({modules:true,script:await readFile(scriptPath,'utf8'),compatibilityDate:'2026-09-27',compatibilityFlags:['nodejs_compat'],
    durableObjects:{COORDINATOR:{className:'FixtureVideo',useSQLite:true}},r2Buckets:['MEDIA']}),resourcePersistencePath:path.join(directory,'storage')};
  let mf=new Miniflare(options);t.after(()=>mf.dispose());
  const fixture=await videoFixture(),manifest=fixture.manifest,id=await videoManifestHash(manifest),report=videoReport(id,manifest);
  let bucket=(await mf.getBindings<{MEDIA:R2Bucket}>()).MEDIA;for(const asset of videoAssets(manifest))await bucket.put(asset.objectKey,new Uint8Array(fixture.files.get(asset.id)!));
  const call=(name:string,route:string,body?:unknown)=>mf.dispatchFetch(`https://test${route}?name=${name}`,{method:body===undefined?'GET':'POST',body:body===undefined?undefined:JSON.stringify(body)});
  const snapshot=async(name:string)=>(await (await call(name,'/state')).json()) as Snapshot;
  const accept=(name:string)=>call(name,'/accept',{manifest,report});
  await call('cancelled-before-start','/cancel',{id});assert.equal((await accept('cancelled-before-start')).status,409);
  assert.equal((await snapshot('cancelled-before-start')).state.budget,null);
  await Promise.all([accept('success'),accept('success')]);
  assert.equal((await snapshot('success')).state.budget.committedCents,50);
  await Promise.all([call('success','/advance'),call('success','/advance')]);
  let state=await snapshot('success');assert.equal(state.job.status,'ready');assert.equal(state.starts,1);assert.equal(state.cleaned,true);assert.equal(state.stopped,true);
  const stored=await bucket.get(state.job.objectKey!);assert.equal(stored!.customMetadata?.watermarked,'true');assert.equal(stored!.size,3);
  // Publication sauvée dans R2 mais état ready perdu : aucune seconde exécution.
  await call('success','/publishing',{});await mf.dispose();mf=new Miniflare(options);bucket=(await mf.getBindings<{MEDIA:R2Bucket}>()).MEDIA;
  await call('success','/advance');await accept('success');state=await snapshot('success');assert.equal(state.job.status,'ready');assert.equal(state.starts,1);
  await call('success','/cancel',{id});assert.equal((await accept('success')).status,200);
  await call('success','/pause',{});await accept('success');assert.equal((await snapshot('success')).state.budget.attempts,1);
  await accept('cold-start');await call('cold-start','/control',{unavailable:1});await call('cold-start','/advance');
  state=await snapshot('cold-start');assert.equal(state.job.status,'staging');assert.equal(state.starts,0);
  assert.equal(state.job.diagnostic?.httpStatus,503);assert.equal(state.state.budget.committedCents,50);
  await call('cold-start','/advance');state=await snapshot('cold-start');assert.equal(state.job.status,'ready');assert.equal(state.starts,1);
  await accept('unavailable');await call('unavailable','/control',{unavailable:4});
  for(let i=0;i<3;i++)await call('unavailable','/advance');
  state=await snapshot('unavailable');assert.equal(state.job.status,'failed');assert.equal(state.job.error,'VIDEO_CONTAINER_UNAVAILABLE');
  assert.equal(state.starts,0);assert.equal(state.job.failures,2);assert.equal(state.stopped,true);
  const failedAt=state.job.updatedAt;await call('unavailable','/pause',{});
  assert.equal((await call('unavailable','/retry',{failedAt:failedAt-1})).status,409);
  await Promise.all([1,2].map(()=>call('unavailable','/retry',{failedAt})));
  state=await snapshot('unavailable');assert.equal(state.job.status,'accepted');assert.equal(state.job.attempt,2);
  assert.equal(state.state.budget.committedCents,100);assert.equal(state.state.budget.attempts,2);
  const history=await (await call('unavailable','/history')).json() as VideoJob[];
  assert.equal(history.length,2);assert.equal(history[0].error,'VIDEO_CONTAINER_UNAVAILABLE');
  await call('unavailable','/control',{unavailable:0});await call('unavailable','/advance');
  state=await snapshot('unavailable');assert.equal(state.job.status,'ready');assert.equal(state.starts,1);
  await call('unavailable','/retry',{failedAt});assert.equal((await snapshot('unavailable')).state.budget.attempts,2);
  assert.equal((await call('unavailable','/retry',{failedAt:failedAt+1})).status,409);
  await accept('crash');await call('crash','/control',{hold:true});await call('crash','/advance');
  assert.equal((await snapshot('crash')).job.status,'rendering');await call('crash','/control',{stopped:true});await call('crash','/advance');
  state=await snapshot('crash');assert.equal(state.job.error,'VIDEO_RENDER_INTERRUPTED');assert.equal(state.starts,1);assert.equal(state.state.budget.committedCents,50);
  await accept('timeout');await call('timeout','/control',{clock:Date.now()+700_000});await call('timeout','/advance');
  state=await snapshot('timeout');assert.equal(state.job.error,'VIDEO_TIMEOUT');assert.equal(state.starts,0);assert.equal(state.stopped,true);
  await accept('stale-cancel');await call('stale-cancel','/control',{hold:true});await call('stale-cancel','/advance');
  await call('stale-cancel','/cancel',{id});
  const next=structuredClone(manifest);next.jobId='job-next';
  for(const asset of videoAssets(next)){asset.objectKey=asset.objectKey.replace(`/jobs/${manifest.jobId}/`,'/jobs/job-next/');await bucket.put(asset.objectKey,new Uint8Array(fixture.files.get(asset.id)!));}
  const nextId=await videoManifestHash(next);await call('stale-cancel','/accept',{manifest:next,report:videoReport(nextId,next)});await call('stale-cancel','/advance');
  await call('stale-cancel','/cancel',{id});state=await snapshot('stale-cancel');
  assert.equal(state.job.id,nextId);assert.equal(state.job.status,'rendering');assert.equal(state.stopped,false);
  await call('stale-cancel','/cancel',{id:nextId});
  // Paired outputs use the same rendered job. Both objects are required before ready.
  const anonymous=await videoFixture('anonymous'),anonymousId=await videoManifestHash(anonymous.manifest);
  const paired={...videoReport(anonymousId,anonymous.manifest),preview:{...videoReport(anonymousId,anonymous.manifest,new Uint8Array([3,2,1])),watermarked:true}};
  for(const asset of videoAssets(anonymous.manifest))await bucket.put(asset.objectKey,new Uint8Array(anonymous.files.get(asset.id)!));
  await call('anonymous','/accept',{manifest:anonymous.manifest,report:paired});await call('anonymous','/advance');
  state=await snapshot('anonymous');assert.equal(state.job.status,'ready');assert.equal(state.starts,1);assert.equal(state.state.budget.committedCents,80);
  assert.equal((await bucket.head(state.job.objectKey!))!.customMetadata!.watermarked,'false');
  assert.equal((await bucket.head(videoPreviewKey(anonymous.manifest,anonymousId)))!.customMetadata!.watermarked,'true');
  await call('anonymous','/publishing',{});await call('anonymous','/advance');assert.equal((await snapshot('anonymous')).starts,1);
  assert.equal((await snapshot('anonymous')).job.status,'ready');
  await call('missing-preview','/accept',{manifest:anonymous.manifest,report:videoReport(anonymousId,anonymous.manifest)});await call('missing-preview','/advance');
  assert.equal((await snapshot('missing-preview')).job.error,'VIDEO_PREVIEW_INVALID');
  assert.equal((await snapshot('missing-preview')).state.budget.committedCents,80);
  await bucket.delete(manifest.photos[0].objectKey);await accept('missing');await call('missing','/advance');
  state=await snapshot('missing');assert.equal(state.job.error,'VIDEO_ASSET_MISSING');assert.equal(state.starts,0);assert.equal(state.state.active,null);
});
