// Shared with small client utilities; article bodies are only imported by public server pages.
export const blogTopics = [
  {slug: 'marketing-immobilier-ia-agence', heading: 'Marketing immobilier IA : automatiser la communication de votre agence'},
  {slug: 'un-mandat-sept-contenus-immobiliers', heading: '1 mandat, 7 contenus : décliner une annonce immobilière'},
  {slug: 'reel-immobilier-instagram-scripts', heading: 'Reel immobilier Instagram : 7 scripts pour présenter un bien'},
  {slug: 'video-immobiliere-photos-duree-montage', heading: 'Vidéo immobilière à partir de photos : durée, rythme et montage'},
  {slug: 'voix-off-immobiliere-exemples-textes', heading: 'Voix off immobilière : rédiger un texte naturel, avec exemples'},
  {slug: 'animation-photo-immobiliere-ia-fidelite', heading: 'Animation photo immobilière IA : garder une présentation fidèle du bien'},
  {slug: 'musique-video-immobiliere-droits-mixage', heading: 'Musique pour une vidéo immobilière : droits, choix et mixage'},
  {slug: 'calendrier-editorial-immobilier', heading: 'Calendrier éditorial immobilier : un planning sur quatre semaines'},
  {slug: 'rediger-annonce-immobiliere-legende', heading: 'Rédiger une annonce immobilière et sa légende pour les réseaux sociaux'},
  {slug: 'cout-video-immobiliere-budget-credits', heading: 'Combien coûte une vidéo immobilière ? Budget, crédits et coût par mandat'},
  {slug: 'story-instagram-immobiliere-scenarios', heading: 'Story Instagram immobilière : 5 scénarios pour faire découvrir un bien'},
  {slug: 'tiktok-immobilier-videos-agence', heading: 'TikTok immobilier : préparer vos premières vidéos d’agence'},
  {slug: 'youtube-shorts-immobilier-agence', heading: 'YouTube Shorts immobilier : donner une nouvelle destination à vos vidéos'},
  {slug: 'photos-immobilieres-smartphone', heading: 'Photos immobilières au smartphone : une méthode avant le montage vidéo'},
  {slug: 'sous-titres-video-immobiliere-lisibilite', heading: 'Sous-titres de vidéo immobilière : rester lisible, même sans le son'},
  {slug: 'identite-visuelle-agence-immobiliere-videos', heading: 'Identité visuelle d’agence immobilière : des vidéos cohérentes d’un mandat à l’autre'},
  {slug: 'validation-video-immobiliere-vendeur', heading: 'Validation d’une vidéo immobilière : recueillir des retours précis du vendeur'},
  {slug: 'envoyer-video-immobiliere-acquereur', heading: 'Envoyer une vidéo immobilière à un acquéreur : messages et suivi'},
  {slug: 'mesurer-performance-video-immobiliere', heading: 'Mesurer la performance d’une vidéo immobilière, au-delà des vues'},
  {slug: 'video-annonce-location-immobiliere', heading: 'Vidéo d’annonce de location immobilière : présenter le logement et ses conditions'},
] as const;
