import type {BlogArticle} from '../types';

export const redactionArticle: BlogArticle = {
  slug: 'rediger-annonce-immobiliere-legende', title: 'Rédiger une annonce immobilière et une légende — BienVu',
  heading: 'Rédiger une annonce immobilière et sa légende pour les réseaux sociaux',
  description: 'Rédigez une annonce immobilière claire et déclinez sa légende : faits vérifiés, structure, exemples de textes et contrôle des mentions avant diffusion.',
  excerpt: 'Une base de faits, un récit lisible et des variantes adaptées aux supports : la méthode pour écrire autour de vos mandats.',
  category: 'redaction', keyword: 'rédiger annonce immobilière', image: 'paris', imageAlt: 'Appartement lumineux illustrant la rédaction d’une annonce immobilière',
  intro: [
    'Rédiger une annonce immobilière commence par réunir les faits qui permettent au lecteur de comprendre le bien. Le texte doit donner des repères sur sa localisation, sa configuration, son prix et ses particularités. La légende destinée aux réseaux sociaux reprend cette base avec une ouverture adaptée au support.',
    'Préparez donc une source de vérité pour le mandat, puis déclinez les textes. Vous éviterez les contradictions entre la fiche, la voix off et les publications. Les exemples suivants sont des extraits rédactionnels fictifs ; ils sont à compléter avec les caractéristiques et les mentions applicables à votre annonce.',
  ],
  takeaways: ['Séparez les faits confirmés, les informations à compléter et les hypothèses.', 'Choisissez des caractéristiques précises plutôt que des superlatifs.', 'Relisez la cohérence et les mentions de chaque support avant publication.'],
  sections: [
    {id: 'faits', title: 'Réunir les informations avant d’écrire', paragraphs: [
      'Consignez le type de bien, la ville, la surface, les pièces, le prix et les équipements. Ajoutez la configuration, les espaces extérieurs et les informations du dossier que vous pouvez confirmer. Une photo peut illustrer un argument ; elle ne permet pas toujours d’en déduire une caractéristique technique.',
      'Distinguez le nombre de pièces du nombre de chambres et précisez les unités. Si une donnée manque, gardez-la à compléter plutôt que d’utiliser une approximation. La même vigilance s’applique aux temps de trajet, à l’exposition, aux possibilités de travaux et aux rendements locatifs.',
    ], list: {items: ['Faits confirmés : ils peuvent alimenter le texte et la vidéo.', 'Informations absentes : elles restent à compléter dans le dossier.', 'Hypothèses d’usage : elles demandent une formulation et une vérification adaptées.', 'Informations évolutives : prix, disponibilité et conditions doivent être recontrôlés.']}},
    {id: 'structure', title: 'Organiser une annonce qui se lit facilement', paragraphs: [
      'Le premier paragraphe situe le bien et sa configuration. Le suivant décrit les espaces de vie, puis les pièces complémentaires et l’extérieur. Terminez par les informations pratiques, les éléments nécessaires à l’annonce et le contact. Cet ordre aide à retrouver rapidement une donnée.',
      'Les phrases doivent expliquer une caractéristique ou une relation entre les espaces. « La cuisine est accessible depuis le séjour » apporte un repère lorsque c’est confirmé. Des qualificatifs comme « magnifique » ou « idéal » prennent moins de place lorsque les faits parlent déjà du bien.',
    ], examples: [{title: 'Une ouverture factuelle', text: 'À [ville], découvrez cet appartement de [surface] m² et [nombre] pièces. Le séjour et [autre espace confirmé] organisent la partie principale du logement. [Description documentée de la configuration].', note: 'Extrait de rédaction à compléter, et non modèle exhaustif d’annonce réglementaire.'}]},
    {id: 'legende', title: 'Transformer la fiche en légende de publication', paragraphs: [
      'Choisissez l’angle de la publication, puis reprenez les faits correspondants. Une vidéo générale peut situer le bien et présenter ses espaces. Une publication sur la terrasse peut commencer directement par cet élément. La légende complète ce que l’image permet de voir.',
      'Préparez un appel à l’action qui correspond à l’étape suivante : demander la fiche, obtenir une précision ou connaître les créneaux de visite. Ajoutez le moyen de contact et les informations nécessaires à votre support. Vérifiez le comportement du lien et la présentation finale dans le réseau utilisé.',
    ], examples: [{title: 'Extrait pour une première publication', text: 'Un [type de bien] à découvrir à [ville]. [Nombre] pièces, [surface] m² et [atout vérifié] : voici les premiers repères de ce mandat. Regardez les images, puis contactez notre agence pour recevoir les informations complètes.', note: 'Ajoutez le prix, les honoraires et les autres mentions requises selon le bien et la publication.'}, {title: 'Extrait pour un détail', text: 'Aujourd’hui, un regard sur [espace confirmé] de ce bien à [ville]. [Description factuelle]. Vous souhaitez connaître la configuration complète ? Notre agence vous transmet la fiche et les informations de visite.'}]},
    {id: 'mentions', title: 'Contrôler les mentions de l’annonce', paragraphs: [
      'La DGCCRF rappelle que les annonces doivent présenter les informations applicables sur les honoraires et la performance énergétique. Les indications relatives au DPE, aux émissions et aux dépenses énergétiques concernent aussi les annonces diffusées sur les plateformes numériques et les réseaux sociaux. Les détails dépendent du bien et du type de transaction.',
      'Les fiches Service Public précisent les règles pour une vente ou une location, notamment les informations sur le prix, les diagnostics et les risques. Utilisez ces références avec le dossier du mandat pour vérifier votre publication. Une courte vidéo ou une légende ne dispense pas de contrôler les mentions requises ; les exemples de cet article ne constituent pas une annonce complète.',
    ], sources: [{url: 'https://www.economie.gouv.fr/dgccrf/les-fiches-pratiques/professionnels-de-limmobilier-les-regles-connaitre', label: 'DGCCRF — règles applicables aux professionnels de l’immobilier'}, {url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F32061', label: 'Service Public — mentions d’une annonce de vente'}, {url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F35323', label: 'Service Public — mentions d’une annonce de location'}]},
    {id: 'ia', title: 'Donner à l’IA une base qui reste vérifiable', paragraphs: [
      'Une description détaillée aide à préparer un texte cohérent. Écrivez les caractéristiques avec leurs unités et indiquez clairement la transaction. Une phrase comme « Je vends une maison à Lyon pour 200 000 €, avec trois pièces » donne déjà plusieurs repères à confirmer dans le formulaire.',
      'Dans BienVu, vous pouvez démarrer depuis une description puis vérifier les champs préparés. Le formulaire reste le lieu de contrôle avant la création. Relisez en particulier le prix, la surface et la différence entre pièces et chambres ; l’extraction n’a pas à compléter une information absente.',
    ]},
    {id: 'variantes', title: 'Garder la cohérence entre annonce, voix et publications', paragraphs: [
      'Conservez le texte de référence avec le mandat et identifiez les versions diffusées. Lorsqu’un prix change, vérifiez la fiche, les textes visibles dans les vidéos, les légendes et les programmations encore à venir. Une ancienne version peut rester dans un calendrier si personne ne fait ce lien.',
      'La voix off peut raccourcir la formulation tout en conservant les faits. La légende peut développer un détail. Le visuel peut mettre en avant quelques chiffres. Relisez ces trois supports ensemble pour vérifier qu’ils décrivent bien le même logement et les mêmes conditions.',
    ]},
    {id: 'relecture', title: 'Une dernière relecture en cinq questions', paragraphs: [
      'Demandez à une autre personne de lire la publication sans explication. Peut-elle identifier le type de bien, sa localisation et l’action proposée ? Ses questions permettent souvent de repérer une phrase vague ou une information difficile à retrouver.',
      'Faites ensuite une vérification avec le dossier. Le texte doit rester lisible, précis et à jour au moment de sa sortie. Une relecture courte et documentée est plus facile à reproduire quand elle fait partie du parcours de chaque mandat.',
    ], list: {ordered: true, items: ['Les chiffres correspondent-ils au dossier validé ?', 'Chaque argument repose-t-il sur une information confirmée ?', 'Les versions racontent-elles la même configuration ?', 'Les mentions applicables au support sont-elles présentes ?', 'Le lecteur sait-il comment obtenir la suite des informations ?']}},
  ],
  faqs: [{question: 'Peut-on reprendre exactement le texte de l’annonce dans la voix off ?', answer: 'Vous pouvez partir des mêmes faits, puis adapter les phrases à l’écoute et à la durée. La fiche complète et ses mentions restent à vérifier séparément.'}, {question: 'Faut-il ajouter de nombreux hashtags à la légende ?', answer: 'Choisissez surtout un texte compréhensible, des informations exactes et une action claire. Vous pouvez tester des repères locaux pertinents sans remplacer le contenu par une liste de mots-clés.'}],
  related: ['video-annonce-location-immobiliere', 'envoyer-video-immobiliere-acquereur', 'un-mandat-sept-contenus-immobiliers'],
  links: [{path: '/comment-ca-marche', label: 'Préparer les informations dans BienVu'}, {path: '/sources', label: 'Vérifier les sources d’import disponibles'}],
};
