-- Private upload journal; paths are generated by the server and never supplied
-- by the browser. Kept until import cleanup so in-flight exports remain valid.
CREATE TABLE editor_music_assets (
  id TEXT PRIMARY KEY NOT NULL,
  agency_id TEXT NOT NULL,
  import_id TEXT NOT NULL,
  asset_json TEXT NOT NULL CHECK(json_valid(asset_json)),
  object_key TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL,
  FOREIGN KEY(agency_id,import_id) REFERENCES listing_imports(agency_id,id) ON DELETE CASCADE
);
CREATE INDEX editor_music_import ON editor_music_assets(agency_id,import_id);
