import {bundle} from '@remotion/bundler';
import {ensureBrowser} from '@remotion/renderer';
import path from 'node:path';
import {copyFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {root, fixturesDir, bundleDir} from './paths';
await bundle({entryPoint:path.join(root,'packages/video/src/index.tsx'),publicDir:fixturesDir,outDir:bundleDir});
await copyFile(path.join(root,'apps/web/public/fonts/inter-tight.woff2'),path.join(bundleDir,'public/video-font.woff2'));
await copyFile(path.join(root,'apps/web/public/fonts/anton-regular.ttf'),path.join(bundleDir,'public/video-display.ttf'));
await copyFile(path.join(root,'apps/web/public/fonts/instrument-serif.woff2'),path.join(bundleDir,'public/video-serif.woff2'));
const require=createRequire(import.meta.url),maplibre=path.dirname(require.resolve('maplibre-gl/package.json'));
for(const name of ['maplibre-gl.mjs','maplibre-gl-worker.mjs','maplibre-gl-shared.mjs'])await copyFile(path.join(maplibre,'dist',name),path.join(bundleDir,'public',name));
await copyFile(path.join(maplibre,'LICENSE.txt'),path.join(bundleDir,'public/maplibre-LICENSE.txt'));
if(!process.env.REMOTION_BROWSER_EXECUTABLE)await ensureBrowser();
