'use client';
import {useEffect,useState} from 'react';
import type {FinanceReport,FinanceVideo} from '../lib/profitability';
const euro=(micros:number|null|undefined)=>micros==null?'À rapprocher':(micros/1e6).toLocaleString('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:4});
const today=()=>new Date().toISOString().slice(0,10);
const csv=(v:unknown)=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';
function exportRows(data:FinanceReport,agencies:boolean){const lines=agencies?[
 ['Agence','Vidéos','Recettes affectées HT EUR','Coûts EUR','Frais Stripe affectés EUR','Marge contributive EUR','Rapprochements manquants','Encaissements HT EUR'],
 ...data.agencies.map(a=>[a.name,a.videos,a.revenueMicros/1e6,a.costMicros/1e6,a.feeMicros/1e6,a.marginMicros==null?'':a.marginMicros/1e6,a.incomplete,a.cashHtMicros/1e6])]:[
 ['ID','Agence','Vidéo','Date UTC','État','Crédits utilisés','Recettes affectées HT EUR','Coûts EUR','Frais Stripe affectés EUR','Marge contributive EUR','Fournisseurs manquants','Frais à rapprocher'],
 ...data.videos.map(v=>[v.id,v.agency,v.title,v.at,v.status,v.credits,v.revenueMicros/1e6,v.costMicros/1e6,v.feeMicros/1e6,v.marginMicros==null?'':v.marginMicros/1e6,v.missingProviders,v.feesMissing])];
 const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(l=>l.map(csv).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`bienvu-rentabilite-${data.mode}-${agencies?'agences':'videos'}-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function AdminFinance(){
 const [mode,setMode]=useState<'test'|'live'>('test'),[from,setFrom]=useState('2000-01-01'),[until,setUntil]=useState(today),[q,setQ]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(0),[tab,setTab]=useState<'videos'|'agencies'|'expenses'>('videos'),[data,setData]=useState<FinanceReport|null>(null),[revision,setRevision]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState(false),[allocate,setAllocate]=useState<string|null>(null),[voidId,setVoidId]=useState<string|null>(null),[reason,setReason]=useState('');
 const [provider,setProvider]=useState('cloudflare'),[kind,setKind]=useState('fixed'),[reference,setReference]=useState(''),[currency,setCurrency]=useState('EUR'),[original,setOriginal]=useState(''),[eur,setEur]=useState(''),[quantity,setQuantity]=useState(''),[periodFrom,setPeriodFrom]=useState(today),[periodUntil,setPeriodUntil]=useState(today),[paidAt,setPaidAt]=useState(today),[note,setNote]=useState(''),[covers,setCovers]=useState(false),[selected,setSelected]=useState<Record<string,number>>({});
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(q);setPage(0);},300);return()=>clearTimeout(timer);},[q]);
 useEffect(()=>{const c=new AbortController();setData(null);setError('');setSelected({});const params=new URLSearchParams({mode,from,until,q:query,page:String(page)});
  void fetch('/api/admin/finance?'+params,{signal:c.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<FinanceReport>;}).then(setData).catch(()=>{if(!c.signal.aborted)setError('Les données financières ne peuvent pas être chargées. Vérifiez les dates puis actualisez.');});return()=>c.abort();},[mode,from,until,query,page,revision]);
 async function action(input:unknown){if(busy)return false;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/admin/finance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}),body=await r.json() as {updated?:number;unavailable?:number};if(!r.ok)throw Error(r.status===409?'Une synchronisation ou une écriture identique est déjà en cours. Réessayez dans une minute.':'Modification refusée. Vérifiez le justificatif, la période et les vidéos choisies.');setNotice(body.updated===undefined?'Modification enregistrée et conservée dans le journal.':`${body.updated} paiement(s) rapproché(s), ${body.unavailable} encore indisponible(s).`);setRevision(v=>v+1);return true;}catch(e){setError(e instanceof Error?e.message:'Modification indisponible.');return false;}finally{setBusy(false);}}
 const currentExpense=data?.expenses.find(e=>e.id===allocate),unitSum=Object.values(selected).reduce((s,n)=>s+n,0);
 const assignments=Object.entries(selected).map(([jobId,units])=>({jobId,units,covers}));
 async function save(){if(allocate){if(await action({action:'allocate',expenseId:allocate,allocations:assignments})){setAllocate(null);setForm(false);}return;}
  const cents=(s:string)=>Math.round(Number(s.replace(',','.'))*100);if(await action({action:'expense',provider,kind,reference,mode,currency,originalMinor:currency==='EUR'?cents(eur):cents(original),eurCents:cents(eur),quantity:kind==='prepaid'?Number(quantity):unitSum,from:periodFrom,until:periodUntil,paidAt,note,allocations:assignments})){setForm(false);setReference('');setOriginal('');setEur('');setNote('');}}
 function openExpense(){setAllocate(null);setForm(!form);setPeriodFrom(from==='2000-01-01'?today().slice(0,8)+'01':from);setPeriodUntil(until);setSelected({});setCovers(false);}
 return <div className="admin-finance"><p className="admin-muted">Les recettes HT sont réparties sur les crédits réellement consommés. Les frais proviennent des transactions Stripe ; les coûts fournisseurs proviennent des justificatifs saisis ci-dessous. Une marge reste « à rapprocher » tant qu’un coût ou des frais manquent.</p>
  <div className="admin-finance-toolbar"><label>Paiements<select value={mode} onChange={e=>{setMode(e.target.value as 'test'|'live');setPage(0);setForm(false);}}><option value="test">Test Stripe</option><option value="live">Réels</option></select></label><label>Du<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(0);}}/></label><label>Au<input type="date" value={until} max={today()} onChange={e=>{setUntil(e.target.value);setPage(0);}}/></label><label>Vidéo ou agence<input type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher…"/></label><button className="admin-button" type="button" disabled={busy} onClick={()=>void action({action:'stripe_sync'})}>Rapprocher Stripe</button><button className="admin-button" type="button" onClick={()=>setRevision(n=>n+1)}>Actualiser</button></div>
  {mode==='test'&&<p className="admin-finance-test">Les recettes affichées sont simulées par Stripe. Les coûts fournisseurs saisis peuvent correspondre à des dépenses réelles de ces tests.</p>}
  {error&&<p role="alert" className="admin-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {data?<><div className="admin-metrics">{[['Recettes affectées HT',euro(data.summary.revenueMicros)],['Coûts fournisseurs affectés',euro(data.summary.costMicros)],['Frais Stripe affectés connus',euro(data.summary.feeMicros)],['Marge contributive',euro(data.summary.marginMicros)],['Vidéos à rapprocher',data.summary.incomplete],['Crédits prépayés fournisseurs non affectés',euro(data.summary.unassignedCostMicros)]].map(([label,value])=><div className="admin-metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
  <p className="admin-muted">Encaissements HT sur la période : {euro(data.summary.cashHtMicros)} · frais Stripe connus : {euro(data.summary.cashFeeMicros)} · {data.summary.cashFeesMissing} paiement(s) à rapprocher. Les stocks prépayés sont exclus du coût des vidéos jusqu’à leur affectation.</p>
  <nav className="admin-finance-tabs" aria-label="Données financières">{([['videos','Par vidéo'],['agencies','Par agence'],['expenses','Justificatifs & journal']] as const).map(([id,label])=><button type="button" key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}<button type="button" className="admin-button" onClick={openExpense}>{form?'Fermer la saisie':'Ajouter un coût réel'}</button></nav>
  {form&&<section className="admin-card admin-finance-form"><h3>{allocate?'Affecter le prépaiement':'Rapprocher une dépense fournisseur'}</h3>{allocate?<p>{currentExpense?.reference} · {euro((currentExpense?.eurCents??0)*10000)} · {currentExpense?.quantity} unités, {currentExpense?.allocatedUnits} déjà affectées.</p>:<div className="admin-finance-fields"><label>Fournisseur<select value={provider} onChange={e=>setProvider(e.target.value)}>{['cloudflare','openai','google','fish','runway','other'].map(p=><option key={p}>{p}</option>)}</select></label><label>Nature<select value={kind} onChange={e=>setKind(e.target.value)}><option value="usage">Consommation facturée</option><option value="fixed">Coût fixe à répartir</option><option value="prepaid">Crédits API prépayés</option><option value="credit_note">Avoir fournisseur</option></select></label><label>Référence du justificatif<input value={reference} onChange={e=>setReference(e.target.value)} maxLength={120} placeholder="Facture / reçu…"/></label><label>Devise d’origine<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>EUR</option><option>USD</option></select></label>{currency==='USD'&&<label>Montant du justificatif en USD<input inputMode="decimal" value={original} onChange={e=>setOriginal(e.target.value)} placeholder="0,00"/></label>}<label>Montant réellement payé en EUR<input inputMode="decimal" value={eur} onChange={e=>setEur(e.target.value)} placeholder="0,00"/></label>{kind==='prepaid'&&<label>Quantité de crédits API achetés<input type="number" min={1} value={quantity} onChange={e=>setQuantity(e.target.value)}/></label>}<label>Début de période<input type="date" value={periodFrom} onChange={e=>setPeriodFrom(e.target.value)}/></label><label>Fin de période<input type="date" value={periodUntil} onChange={e=>setPeriodUntil(e.target.value)}/></label><label>Date du paiement<input type="date" max={today()} value={paidAt} onChange={e=>setPaidAt(e.target.value)}/></label><label className="admin-finance-note">Justification et méthode de répartition<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={500} placeholder="Source du montant, unité utilisée, périmètre couvert…"/></label></div>}
   <p>Sélectionnez les vidéos de la liste ci-dessous. Pour les coûts fixes, 1 unité par vidéo répartit le montant à parts égales. Pour Runway prépayé, indiquez les crédits API réellement consommés.</p><label className="admin-finance-cover"><input type="checkbox" checked={covers} onChange={e=>setCovers(e.target.checked)}/>Ce justificatif couvre entièrement ce fournisseur pour chaque vidéo sélectionnée.</label><p>{Object.keys(selected).length} vidéo(s) · {unitSum} unités affectées.</p><button type="button" className="admin-button admin-button-primary" disabled={busy||(!allocate&&(!reference.trim()||eur.trim()===''||note.trim().length<5))||(!unitSum&&(Boolean(allocate)||kind!=='prepaid'))} onClick={()=>void save()}>{busy?'Enregistrement…':'Enregistrer le rapprochement'}</button>
  </section>}
  {(tab==='videos'||form)&&<><div className="admin-finance-table-top"><p>{data.total} vidéo(s) · page {page+1}</p><button type="button" className="admin-button" onClick={()=>exportRows(data,false)}>Exporter cette page en CSV</button></div><div className="admin-table-scroll"><table className="admin-table"><thead><tr>{form&&<th>Affecter / unités</th>}<th>Vidéo</th><th>Agence</th><th>Crédits</th><th>Recettes HT</th><th>Coût réel</th><th>Frais Stripe</th><th>Marge</th></tr></thead><tbody>{data.videos.map(v=><tr key={v.id}>{form&&<td><input type="checkbox" aria-label={'Affecter '+v.title} checked={Boolean(selected[v.id])} onChange={e=>setSelected(s=>{const next={...s};if(e.target.checked)next[v.id]=1;else delete next[v.id];return next;})}/>{selected[v.id]&&<input className="admin-finance-units" aria-label={'Unités pour '+v.title} type="number" min={1} max={100000000} value={selected[v.id]} onChange={e=>setSelected(s=>({...s,[v.id]:Math.max(1,Number(e.target.value))}))}/>}</td>}<td><a href={'/historique/'+v.id}>{v.title}</a><small>{new Date(v.at).toLocaleString('fr-FR')} · {v.status}</small></td><td>{v.agency??'Essai anonyme'}</td><td>{v.credits}</td><td>{euro(v.revenueMicros)}</td><td>{euro(v.costMicros)}{v.missingProviders&&<small>Manque : {v.missingProviders}</small>}</td><td>{euro(v.feeMicros)}{v.feesMissing>0&&<small>Frais incomplets</small>}</td><td>{euro(v.marginMicros)}</td></tr>)}</tbody></table></div><div className="admin-finance-pagination"><button type="button" className="admin-button" disabled={!page} onClick={()=>setPage(n=>n-1)}>Précédent</button><button type="button" className="admin-button" disabled={(page+1)*50>=data.total} onClick={()=>setPage(n=>n+1)}>Suivant</button></div></>}
  {tab==='agencies'&&<><button type="button" className="admin-button" onClick={()=>exportRows(data,true)}>Exporter les agences affichées</button><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Agence</th><th>Vidéos</th><th>Recettes affectées HT</th><th>Coûts</th><th>Frais affectés</th><th>Marge</th><th>Encaissements HT</th><th>Recettes de crédits non consommés</th></tr></thead><tbody>{data.agencies.map(a=><tr key={a.id}><td>{a.name}</td><td>{a.videos}</td><td>{euro(a.revenueMicros)}</td><td>{euro(a.costMicros)}</td><td>{euro(a.feeMicros)}</td><td>{euro(a.marginMicros)}{a.incomplete>0&&<small>{a.incomplete} vidéo(s) incomplète(s)</small>}</td><td>{euro(a.cashHtMicros)}{a.cashFeesMissing>0&&<small>Frais à rapprocher</small>}</td><td>{euro(a.unassignedRevenueMicros)}</td></tr>)}</tbody></table></div><p className="admin-muted">100 premières agences. Les recettes de crédits non consommés portent sur tout l’historique ; les autres colonnes suivent la période choisie.</p></>}
  {tab==='expenses'&&<><h3>Les 50 derniers justificatifs</h3><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Référence</th><th>Fournisseur</th><th>EUR payé</th><th>Affecté aux vidéos</th><th>Unités</th><th>Action</th></tr></thead><tbody>{data.expenses.map(e=><tr key={e.id}><td>{e.reference}<small>{e.kind} · {e.from} → {e.until}{e.voidedAt?' · annulé':''}</small></td><td>{e.provider}</td><td>{euro(e.eurCents*10000)}</td><td>{euro(e.allocatedMicros)}</td><td>{e.allocatedUnits} / {e.quantity}</td><td>{!e.voidedAt&&<>{e.kind==='prepaid'&&e.allocatedUnits<e.quantity&&<button className="admin-button" type="button" onClick={()=>{setAllocate(e.id);setForm(true);setFrom(e.from);setUntil(e.until);setTab('videos');setSelected({});setCovers(false);}}>Affecter</button>}<button className="admin-button" type="button" onClick={()=>{setVoidId(e.id);setReason('');}}>Annuler ce justificatif</button></>}</td></tr>)}</tbody></table></div>{voidId&&<div className="admin-card"><label>Motif de l’annulation<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={300}/></label><button className="admin-button" type="button" onClick={()=>setVoidId(null)}>Retour</button><button className="admin-button" type="button" disabled={reason.trim().length<5||busy} onClick={()=>void action({action:'void',expenseId:voidId,reason}).then(ok=>{if(ok)setVoidId(null);})}>Confirmer l’annulation</button></div>}<h3>Journal financier · 50 dernières actions</h3>{data.audit.map((a,i)=><p key={i} className="admin-muted">{new Date(a.at).toLocaleString('fr-FR')} · {a.action} · {a.target}</p>)}</>}
  <p className="admin-muted">La marge contributive retire les coûts affectés et les frais Stripe vérifiés des recettes HT affectées. Elle ne représente pas un résultat comptable : coûts non affectés, fiscalité et frais généraux restent à traiter. Un coût nul doit aussi être justifié. Les estimations en dollars et provisions du pilote ne sont jamais considérées comme des factures.</p>
  </>:!error&&<p>Lecture des rapprochements…</p>}
 </div>;
}
export function AdminVideoProfit({jobId}:{jobId:string}){const [data,setData]=useState<FinanceReport|null>(null),[error,setError]=useState('');useEffect(()=>{const c=new AbortController();setData(null);setError('');async function load(){for(const mode of ['live','test']){const r=await fetch('/api/admin/finance?'+new URLSearchParams({jobId,mode}),{signal:c.signal,cache:'no-store'});if(!r.ok)throw Error();const next=await r.json() as FinanceReport;if(next.videos.length){setData(next);return;}}throw Error();}void load().catch(()=>{if(!c.signal.aborted)setError('Rapprochement financier indisponible.');});return()=>c.abort();},[jobId]);const v:FinanceVideo|undefined=data?.videos[0];return <section className="admin-narration-costs"><h3>Rentabilité de cette vidéo</h3>{error?<p>{error}</p>:v?<><p>{data?.mode==='test'?'Recettes Stripe de test · ':''}{v.credits} crédit(s) utilisé(s) · recettes HT affectées : {euro(v.revenueMicros)} · frais Stripe connus : {euro(v.feeMicros)} · coûts justifiés : {euro(v.costMicros)}</p><p>Marge contributive : <strong>{euro(v.marginMicros)}</strong></p>{v.missingProviders&&<p className="admin-muted">Fournisseurs à rapprocher : {v.missingProviders}.</p>}{v.feesMissing>0&&<p className="admin-muted">Des frais Stripe restent à vérifier.</p>}{data?.detail?.costs.map((c,i)=><p key={i}>{c.provider} · {c.reference} · {euro(c.amountMicros)} ({c.units} unités)</p>)}<a href="/admin?view=finance">Ouvrir les rapprochements financiers →</a></>:<p>Chargement…</p>}</section>;}
