'use client';
import type {AdminOverview,AdminSection,AdminTraffic} from '@bienvu/contracts';
import {HomeIcon} from './home-icons';
export type AdminTarget={view:AdminSection|'system';status?:string;from?:string};
const n=(v:number)=>v.toLocaleString('fr-FR');
const usd=(v:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'USD',minimumFractionDigits:6,maximumFractionDigits:6}).format(v/1e6);
const euro=(v:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(v/100);
const percent=(v:number,total:number)=>total?Math.round(v/total*100)+' %':'Non mesuré';
const pageNames:Record<string,string>={home:'Créer une vidéo',login:'Connexion',explorer:'Explorer',offers:'Offres',sources:'Sources compatibles'};
function countryName(country:string){if(country==='XX')return 'Pays inconnu';try{return new Intl.DisplayNames(['fr'],{type:'region'}).of(country)??country;}catch{return country;}}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <article><span>{label}</span><strong>{value}</strong><small>{note}</small></article>;}
export function AdminAttention({data,onFocus}:{data:AdminOverview;onFocus:(target:AdminTarget)=>void}){
  const c=data.counts,b=data.budget,alerts:{title:string;body:string;level:string;target:AdminTarget}[]=[];
  if(b){const used=b.baselineCents+b.importsCents,ratio=used/Math.max(1,b.ceilingCents);
    if(b.paused||ratio>=.8)alerts.push({title:b.paused?'Budget suspendu':ratio>=1?'Plafond budgétaire atteint':'Budget à surveiller',body:`${euro(Math.max(0,b.ceilingCents-used))} de marge dans D1 avant la coupure. Provisions, pas une facture.`,level:b.paused||ratio>=.95?'critical':'warning',target:{view:'system'}});}
  if(c.overdue>0)alerts.push({title:'Générations au-delà du délai',body:`${n(c.overdue)} job(s) actif(s) ont dépassé leur échéance.`,level:'critical',target:{view:'videos',status:'active'}});
  if(c.failedToday>0)alerts.push({title:'Échecs aujourd’hui',body:`${n(c.failedToday)} génération(s) créées aujourd’hui ont échoué.`,level:'warning',target:{view:'videos',status:'failed',from:data.at.slice(0,10)}});
  if(c.openReports>0)alerts.push({title:'Signalements à traiter',body:`${n(c.openReports)} signalement(s) encore ouverts.`,level:'warning',target:{view:'reports'}});
  if(c.delinquentSubscriptions>0)alerts.push({title:'Abonnements à vérifier',body:`${n(c.delinquentSubscriptions)} abonnement(s) en retard ou impayés.`,level:'critical',target:{view:'subscriptions'}});
  if(c.unverifiedUsers>0)alerts.push({title:'Comptes non vérifiés',body:`${n(c.unverifiedUsers)} compte(s). Cela ne prouve pas un échec de livraison e-mail.`,level:'info',target:{view:'users',status:'unverified'}});
  if(!data.config.generations||data.control?.enabled!==1)alerts.push({title:'Nouveaux lancements fermés',body:'Vérifiez les autorisations du service avant une reprise.',level:'info',target:{view:'system'}});
  return <section className="admin-card admin-attention" aria-label="Points d’attention"><div className="admin-card-heading"><h3>Points d’attention</h3><span>{alerts.length} à suivre</span></div>{alerts.length?<div className="admin-alert-grid">{alerts.map(a=><button type="button" className={`admin-alert admin-alert-${a.level}`} key={a.title} onClick={()=>onFocus(a.target)}><span><strong>{a.title}</strong><HomeIcon name="arrow" size={17}/></span><p>{a.body}</p></button>)}</div>:<p className="admin-muted">Aucune alerte dans les registres actuels. La livraison des e-mails et les factures restent à vérifier séparément.</p>}</section>;
}
export function AdminPerformance({data}:{data:AdminOverview}){
  const p=data.performance,completed=p.ready+p.failed;
  return <><div className="admin-insight-metrics admin-performance-metrics"><Metric label="Taux de réussite" value={percent(p.ready,completed)} note={`${n(p.ready)} prêts / ${n(completed)} jobs finalisés`}/><Metric label="Durée moyenne" value={p.averageSeconds===null?'Non mesurée':Math.round(p.averageSeconds)+' s'} note={`${n(p.measuredReady)} / ${n(p.ready)} vidéos prêtes chronométrées`}/><Metric label="Encore en cours" value={n(p.active)} note="Exclus du taux de réussite"/></div>
    <section className="admin-card"><h3>Performance sur {p.days} jours</h3><p className="admin-muted">Jobs créés sur les {p.days} derniers jours calendaires UTC, comptes, anonymes et tests internes inclus. Durée de la création à l’événement « ready », attente et reprises comprises. Un événement absent reste non mesuré ; une purge ultérieure ne change pas le chronométrage.</p><div className="admin-summary-lines"><p><span>Générations enregistrées</span><strong>{n(p.total)}</strong></p><p><span>Terminées avec succès</span><strong>{n(p.ready)}</strong></p><p><span>Échecs</span><strong>{n(p.failed)}</strong></p><p><span>Au-delà de leur échéance, tous les jobs actifs</span><strong>{n(data.counts.overdue??0)}</strong></p></div></section>
    <section className="admin-card admin-insight-spaced"><h3>Erreurs conservées</h3>{data.errors.length?<div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Code</th><th>Étape</th><th>Occurrences</th></tr></thead><tbody>{data.errors.map(e=><tr key={e.code+e.stage}><td>{e.code}</td><td>{e.stage}</td><td>{n(e.count)}</td></tr>)}</tbody></table></div>:<p className="admin-muted">Aucune erreur conservée.</p>}<p className="admin-muted">Registres jobs/imports, toutes dates. Les imports déjà purgés ne sont pas reconstitués.</p></section></>;
}
export function AdminMonthlyCosts({data}:{data:AdminOverview}){
  return <><div className="admin-insight-metrics admin-monthly-costs">{['openai','google'].map(provider=>{const c=data.monthlyCosts.find(c=>c.provider===provider);return <Metric key={provider} label={provider==='openai'?'OpenAI · rédaction':'Google · voix'} value={!c||!c.realCalls?'Aucun appel réel':c.amountMicros===null?'Non mesuré':usd(c.amountMicros)} note={`${c?n(c.measuredCalls)+' / '+n(c.realCalls):'0 / 0'} appels réels mesurés${c&&c.measuredCalls<c.realCalls?' · Total partiel':''}`}/>;})}</div>
    <section className="admin-card"><div className="admin-card-heading"><h3>Appels du mois</h3><span>{data.at.slice(0,7)} · UTC</span></div>{data.monthlyCosts.length?<div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Fournisseur</th><th>Réels</th><th>Mesurés</th><th>Échecs réels</th><th>Fixtures</th><th>Estimation USD</th></tr></thead><tbody>{data.monthlyCosts.map(c=><tr key={c.provider}><td>{c.provider==='openai'?'OpenAI':'Google'}</td><td>{n(c.realCalls)}</td><td>{n(c.measuredCalls)}</td><td>{n(c.failedCalls)}</td><td>{n(c.mockCalls)}</td><td>{c.amountMicros===null?'Non mesuré':usd(c.amountMicros)}{c.measuredCalls<c.realCalls?' · Partiel':''}</td></tr>)}</tbody></table></div>:<p className="admin-muted">Aucun appel enregistré pour ce mois.</p>}<p className="admin-muted">Tarifs conservés : OpenAI avant remise cache, Google avant gratuité. Fixtures exclues des sommes, corrections comprises, reprises du même appel comptées une fois. Une mesure absente ne vaut pas zéro.</p><p className="admin-muted">Hors taxes et conversion. La facture réelle, le rendu Cloudflare, le stockage et la marge commerciale restent inconnus. Provisions EUR dans « Service & budget ».</p></section></>;
}
export function AdminTrafficView({data}:{data:AdminTraffic}){
  const max=Math.max(1,...data.daily.map(r=>r.views));
  return <><div className="admin-insight-metrics admin-traffic-metrics"><Metric label="Pages servies" value={n(data.total)} note={`${data.days} derniers jours calendaires UTC`}/><Metric label="Pays observés" value={n(data.countries.filter(c=>c.country!=='XX').length)} note="Origine réseau approximative"/><Metric label="Premier jour conservé" value={data.firstDay??'Aucune mesure'} note={data.enabled?'Collecte active':'Collecte désactivée'}/></div>
    {!data.enabled&&<p className="admin-notice">La collecte est désactivée. Les agrégats encore conservés restent consultables.</p>}
    <section className="admin-card"><h3>Fréquentation quotidienne</h3>{data.total?<div className="admin-chart admin-traffic-chart" role="img" aria-label={`Pages HTML servies par jour sur ${data.days} jours UTC`}>{data.daily.map((r,i)=><div key={r.day} title={`${r.day} : ${data.firstDay&&r.day<data.firstDay?'aucune donnée conservée':r.views+' pages'}`}><span>{r.views||''}</span><i style={{height:Math.max(2,r.views/max*126),opacity:data.firstDay&&r.day<data.firstDay?0:1}}/><small>{i%5===0||i===data.days-1?r.day.slice(8):''}</small></div>)}</div>:<p className="admin-muted">Aucune page mesurée sur cette période. La collecte ne reconstitue pas les anciennes visites.</p>}</section>
    <div className="admin-dashboard-grid admin-insight-spaced"><section className="admin-card"><h3>Pays d’origine</h3>{data.countries.length?data.countries.map(c=><div className="admin-geography" key={c.country}><span><strong>{countryName(c.country)}</strong><small>{percent(c.views,data.total)} des pages</small></span><strong>{n(c.views)}</strong><div className="admin-meter"><i style={{width:(data.total?c.views/data.total*100:0)+'%'}}/></div></div>):<p className="admin-muted">Aucune origine disponible.</p>}</section><section className="admin-card"><h3>Pages consultées</h3>{data.pages.length?<div className="admin-summary-lines">{data.pages.map(p=><p key={p.page}><span>{pageNames[p.page]??p.page}</span><strong>{n(p.views)}</strong></p>)}</div>:<p className="admin-muted">Aucune page disponible.</p>}</section></div>
    <section className="admin-card admin-insight-spaced"><h3>Ce que ces chiffres mesurent</h3><p className="admin-muted">Chargements HTML réussis des cinq pages publiques suivies, sur le domaine principal. Rechargements et visites de l’administrateur peuvent compter. Les navigations internes sans chargement HTML ne comptent pas. Robots reconnaissables et préchargements exclus ; certains robots peuvent subsister.</p><p className="admin-muted">Le pays fourni par Cloudflare correspond à l’origine réseau et peut être celui d’un VPN. Ce n’est ni une position exacte ni un nombre de personnes uniques. Aucune adresse IP, cookie analytique, identifiant, URL complète, recherche ou référent n’est enregistré. Agrégats conservés environ 31 jours, purge quotidienne.</p></section></>;
}
