'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import type {SeoSummary} from '../lib/seo-analytics';
const channels:Record<string,string>={direct:'Accès direct ou source inconnue',google:'Google',bing:'Bing',search:'Autres moteurs',social:'Réseaux sociaux',internal:'Navigation dans BienVu',other:'Autres sites'};
const n=(value:number)=>value.toLocaleString('fr-FR');
export function AdminSeo() {
  const [data,setData]=useState<SeoSummary|null>(null),[error,setError]=useState('');
  useEffect(()=>{const controller=new AbortController();void fetch('/api/admin?section=seo',{signal:controller.signal,cache:'no-store'}).then(async response=>{if(!response.ok)throw Error();return response.json() as Promise<SeoSummary>;}).then(setData).catch(()=>{if(!controller.signal.aborted)setError('Le suivi SEO ne peut pas être chargé.');});return()=>controller.abort();},[]);
  if(error)return <p className="admin-error" role="alert">{error}</p>;if(!data)return <p role="status">Lecture du suivi SEO…</p>;
  const metrics=['LCP','CLS','INP'];
  return <div className="admin-seo"><p className="admin-muted">30 jours · {data.from} au {data.until} (UTC). {data.enabled?'Collecte activée.':'Collecte désactivée.'} {data.firstDay?`Premiers agrégats : ${data.firstDay}.`:'Les statistiques se rempliront avec les prochaines visites.'}</p>
    <div className="admin-insight-grid"><section className="admin-insight"><h3>Pages publiques vues</h3><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Page</th><th>Chargements</th></tr></thead><tbody>{data.pages.map(row=><tr key={row.page}><td>{row.page==='/explorer/video'?'Vidéos publiques partagées':<Link href={row.page} prefetch={false}>{row.page}</Link>}</td><td>{n(row.views)}</td></tr>)}</tbody></table></div>{!data.pages.length&&<p>Aucune visite enregistrée.</p>}</section>
    <section className="admin-insight"><h3>Sources de trafic</h3><table className="admin-table"><thead><tr><th>Source</th><th>Chargements</th></tr></thead><tbody>{data.channels.map(row=><tr key={row.channel}><td>{channels[row.channel]}</td><td>{n(row.views)}</td></tr>)}</tbody></table><p className="admin-muted">Catégories calculées à partir du référent lorsqu’il est transmis. Son URL n’est jamais conservée. Les visites internes ne constituent pas de nouvelles entrées.</p></section></div>
    <section className="admin-insight"><h3>Expérience de chargement · Core Web Vitals</h3><p className="admin-muted">Mesures du navigateur sur la première page du document, lorsqu’elles sont disponibles. Les changements de page sans rechargement sont exclus. Ce sont des échantillons locaux agrégés, distincts des données de Google Search Console.</p><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Mesure</th><th>Bon</th><th>À améliorer</th><th>Mauvais</th><th>Échantillons</th></tr></thead><tbody>{metrics.map(metric=>{const rows=data.vitals.filter(row=>row.metric===metric),sum=(bucket:string)=>rows.filter(row=>row.bucket===bucket).reduce((total,row)=>total+row.samples,0);return <tr key={metric}><th>{metric}</th><td>{n(sum('good'))}</td><td>{n(sum('needs-improvement'))}</td><td>{n(sum('poor'))}</td><td>{n(rows.reduce((total,row)=>total+row.samples,0))}</td></tr>;})}</tbody></table></div><p className="admin-muted">Seuils « bon » : LCP ≤ 2,5 s · CLS ≤ 0,1 · INP ≤ 200 ms. Pas de score sans mesures.</p><details><summary>Résultats par page</summary><table className="admin-table"><thead><tr><th>Page</th><th>Mesure</th><th>Classe</th><th>Échantillons</th></tr></thead><tbody>{data.vitals.map(row=><tr key={`${row.page}:${row.metric}:${row.bucket}`}><td>{row.page}</td><td>{row.metric}</td><td>{row.bucket==='good'?'Bon':row.bucket==='poor'?'Mauvais':'À améliorer'}</td><td>{n(row.samples)}</td></tr>)}</tbody></table></details></section>
    <section className="admin-insight"><h3>Indexation et conversion</h3><p>Consultez les inscriptions, les vidéos terminées et les paiements confirmés dans <Link href="/admin?view=commercial">Conversion & recettes</Link>. Ces résultats viennent des comptes et paiements réellement enregistrés ; ils ne sont pas attribués individuellement aux visites.</p><p><a href="https://search.google.com/search-console?resource_id=sc-domain%3Abienvu.online" target="_blank" rel="noopener noreferrer">Ouvrir Google Search Console ↗</a> · <a href="/sitemap.xml" target="_blank" rel="noopener noreferrer">Sitemap public ↗</a></p><p className="admin-muted">La propriété doit être vérifiée auprès de Google avant que les impressions, clics et positions puissent être consultés. BienVu n’en invente pas les résultats. Les agrégats locaux sont conservés environ 31 jours, sans cookie analytique ni identifiant de visiteur.</p></section>
  </div>;
}
