'use client';
import {useEffect,useRef,useState} from 'react';
import {qualityCoverage,type AiQualityRun,type AiQualitySettings,type QualityCheck,type QualityVerdict} from '@bienvu/contracts';
import {HomeIcon} from './home-icons';
import '../app/admin/ai-quality.css';

type Data={settings:AiQualitySettings;revision:number;activatedAt:string;runs:AiQualityRun[];nextCursor:string|null;
  counts:{total:number;ready:number;failed:number;awaitingReview:number;sampled:number;accepted:number;problems:number;falsePositives:number;intentional:number};
  checks:{key:string;label:string;pass:number;fail:number;na:number;error:number}[];outbox:{pending:number;sent:number;dead:number};sources:{source:string;n:number}[];
dataset:{count:number};dashboardUrl:string};
type Detail={run:AiQualityRun;payload:{facts:Record<string,unknown>;sourceText:string;finalNarration:string;spokenText:string[];
  audio:{id:string;durationMs:number;rmsDbfs:number}[];mediaAvailable:boolean;historical:boolean;automatic:boolean;costs:{estimatedUsd:number|null;actualUsd:number|null;unknownProviders:string[]};timing:{totalMs:number;renderMs:number|null;voiceMs:number;scriptMs:number}};ledger:{reconciledEur:number|null;actualEur:number|null;missing:string[]};reviewNote:string|null;traceUrl:string};
const money=(n:number|null)=>n===null?'Non mesuré':new Intl.NumberFormat('fr-FR',{style:'currency',currency:'USD',maximumFractionDigits:5}).format(n);
const date=(s:string)=>new Date(s).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'});
const statuses:Record<string,string>={pass:'Conforme',fail:'À vérifier',na:'Non applicable',error:'Erreur technique',pending:'En attente',running:'Évaluation en cours',done:'Évaluée',skipped:'Non échantillonnée',budget:'Budget atteint',failed:'Interrompue',uncertain:'Résultat incertain',ready:'Prête',problem:'Problème confirmé',false_positive:'Faux positif',intentional:'Choix volontaire',accepted:'Validée'};
async function request<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,cache:'no-store'});if(!r.ok)throw Error(r.status===409?'La donnée a changé. Actualisez avant de réessayer.':r.status===401||r.status===403?'Votre connexion administrateur est requise.':'L’opération a échoué. Réessayez.');return r.json() as Promise<T>;}
function Check({check}:{check:QualityCheck}){return <div className={'aiq-check aiq-'+check.status}><div><strong>{check.label}</strong><span>{statuses[check.status]}</span></div><p>{check.reason}</p></div>;}
export function AdminAiQuality({revision}:{revision:number}){
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[local,setLocal]=useState(0),[notice,setNotice]=useState('');
  const [days,setDays]=useState(30),[audience,setAudience]=useState(''),[source,setSource]=useState(''),[flagged,setFlagged]=useState(false),[settings,setSettings]=useState<AiQualitySettings|null>(null);
  const [selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<Detail|null>(null),[detailError,setDetailError]=useState(''),[note,setNote]=useState(''),[verdict,setVerdict]=useState<QualityVerdict>('problem');
  const dialog=useRef<HTMLDialogElement>(null),settingsRevision=useRef(0);
  const params=new URLSearchParams({days:String(days),audience,source,flagged:flagged?'1':'0'});
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');void request<Data>('/api/admin/ai-quality?'+new URLSearchParams({days:String(days),audience,source,flagged:flagged?'1':'0'}),{signal:controller.signal}).then(value=>{
    if(controller.signal.aborted)return;setData(value);setSettings(value.settings);settingsRevision.current=value.revision;
  }).catch(e=>{if(!controller.signal.aborted)setError(String(e.message));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[revision,local,days,audience,source,flagged]);
  useEffect(()=>{if(!selected){if(dialog.current?.open)dialog.current.close();return;}dialog.current?.showModal();setDetail(null);setDetailError('');const controller=new AbortController();
    void request<Detail>('/api/admin/ai-quality?id='+encodeURIComponent(selected),{signal:controller.signal}).then(d=>{if(controller.signal.aborted)return;setDetail(d);setNote(d.reviewNote??'');setVerdict(d.run.review??(d.run.flagged?'problem':'accepted'));}).catch(e=>{if(!controller.signal.aborted)setDetailError(e.message);});return()=>controller.abort();},[selected]);
  async function action(body:Record<string,unknown>,message:string){setBusy(true);setError('');setNotice('');try{await request('/api/admin/ai-quality',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setNotice(message);setLocal(n=>n+1);
      if(selected&&body.id===selected){const d=await request<Detail>('/api/admin/ai-quality?id='+encodeURIComponent(selected));setDetail(d);}
    }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function saveSettings(){if(!settings)return;setBusy(true);setNotice('');try{await request('/api/admin/ai-quality',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({settings,revision:settingsRevision.current})});setNotice('Réglages enregistrés. Ils s’appliquent aux prochains contrôles.');setLocal(n=>n+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function more(){if(!data?.nextCursor)return;setBusy(true);try{const next=await request<Data>('/api/admin/ai-quality?'+params+'&cursor='+encodeURIComponent(data.nextCursor));setData(d=>d?{...d,runs:[...d.runs,...next.runs],nextCursor:next.nextCursor}:next);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="aiq" aria-label="Qualité des générations IA">
    <div className="aiq-intro"><div><h3>Une vidéo réussie, à chaque étape.</h3><p>Contrôles sur les informations confirmées et la narration finale. Une alerte invite à vérifier le contenu ; elle ne bloque pas sa création.</p></div><div className="aiq-actions"><a className="admin-button" href={data?.dashboardUrl??'https://eu.posthog.com/project/299212/ai-observability'} target="_blank" rel="noreferrer">Dashboard PostHog <HomeIcon name="arrow" size={16}/></a><button className="admin-button" disabled={busy} onClick={()=>void action({action:'scan'},'Journaux analysés et télémétrie envoyée. Aucun contenu régénéré.')}>Analyser les journaux</button></div></div>
    {error&&<p className="admin-error" role="alert">{error}</p>}{notice&&<p className="admin-notice" role="status">{notice}</p>}
    <div className="aiq-filters"><label>Période<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 jours</option><option value={30}>30 jours</option><option value={90}>90 jours</option></select></label>
      <label>Origine<select value={audience} onChange={e=>setAudience(e.target.value)}><option value="">Toutes</option><option value="account">Comptes</option><option value="anonymous">Essais sans compte</option><option value="internal">Tests internes</option></select></label>
      <label>Source<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Toutes les sources</option>{data?.sources.map(s=><option key={s.source} value={s.source}>{s.source==='manual'?'Saisie manuelle':s.source}</option>)}</select></label>
      <label className="aiq-toggle"><input type="checkbox" checked={flagged} onChange={e=>setFlagged(e.target.checked)}/>À relire uniquement</label></div>
    {loading?<p role="status">Chargement de la qualité IA…</p>:data&&<>
      <div className="aiq-kpis">{[{label:'Générations observées',n:data.counts.total??0,small:`${data.counts.ready??0} prêtes · ${data.counts.failed??0} interrompues`},
        {label:'À relire',n:data.counts.awaitingReview??0,small:'Alertes sans verdict humain'},
        {label:'Échantillon de relecture',n:data.counts.sampled??0,small:`${data.settings.reviewSamplePercent} % des générations, sans appel IA supplémentaire`},
        {label:'Validées par une personne',n:data.counts.accepted??0,small:'Une lecture ou un téléchargement ne vaut pas validation'}].map(k=><div key={k.label}><span>{k.label}</span><strong>{k.n}</strong><small>{k.small}</small></div>)}</div>
      <div className="aiq-health"><span><i className={data.outbox.dead?'aiq-red':''}/>{data.outbox.pending??0} événements à envoyer · {data.outbox.sent??0} transmis{data.outbox.dead?` · ${data.outbox.dead} en échec`:''}</span><span>{data.dataset.count} cas revus dans le jeu de référence</span>{Boolean(data.outbox.dead)&&<button className="admin-button" disabled={busy} onClick={()=>void action({action:'retry_telemetry'},'Renvoi des événements relancé, sans appel aux fournisseurs IA.')}>Renvoyer les événements en échec</button>}</div>
      <details className="aiq-settings"><summary>Réglages des contrôles et relectures</summary>{settings&&<div>
        <div className="aiq-settings-grid"><label className="aiq-toggle"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>Collecter la qualité IA</label>
          <label>Échantillon de relecture humaine (%)<input type="number" min={0} max={100} value={settings.reviewSamplePercent} onChange={e=>setSettings({...settings,reviewSamplePercent:Number(e.target.value)})}/></label>
          <label>Conservation locale (jours)<input type="number" min={7} max={365} value={settings.retentionDays} onChange={e=>setSettings({...settings,retentionDays:Number(e.target.value)})}/></label></div>
        <p className="aiq-muted">Aucun appel OpenAI, Cartesia ou Runway supplémentaire. Les contrôles lisent les résultats déjà enregistrés. Le style, les nuances, la prononciation et le rendu visuel restent soumis à la relecture humaine. La conservation locale ne change pas la conservation configurée dans PostHog.</p>
        <div className="aiq-actions"><button className="admin-button admin-button-primary" disabled={busy} onClick={()=>void saveSettings()}>Enregistrer les réglages</button><a className="admin-button" href="/api/admin/ai-quality?export=dataset">Exporter le jeu de référence</a></div>
      </div>}</details>
      <div className="aiq-coverage"><h3>Couverture des contrôles</h3><p>Le taux porte sur les contrôles réalisés. Les critères non applicables et les erreurs sont comptés séparément.</p>
        {data.checks.length?<div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Contrôle</th><th>Conformes / contrôlés</th><th>À vérifier</th><th>Non applicables</th><th>Erreurs</th></tr></thead><tbody>{data.checks.map(c=><tr key={c.key}><td>{c.label}</td><td>{c.pass+c.fail?`${Math.round(100*c.pass/(c.pass+c.fail))} %`:'—'}<small>{c.pass} / {c.pass+c.fail}</small></td><td>{c.fail}</td><td>{c.na}</td><td>{c.error}</td></tr>)}</tbody></table></div>:<p>Aucun contrôle pour cette période. Les prochaines générations alimenteront cette vue.</p>}</div>
      <div className="aiq-run-list"><h3>Générations et relectures</h3>{!data.runs.length?<div className="admin-empty">Aucune génération pour ces critères.</div>:<div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Bien</th><th>Contrôles</th><th>Évaluation</th><th>Coût estimé connu</th><th>Relecture</th><th/></tr></thead><tbody>{data.runs.map(run=>{const coverage=qualityCoverage(run.checks);return <tr key={run.id}><td><strong>{run.title}</strong><small>{date(run.completedAt)} · {run.sourceHost??'Saisie manuelle'} · {run.audience==='account'?'Compte':run.audience==='anonymous'?'Sans compte':'Interne'}</small></td><td><span className={'aiq-status aiq-'+(coverage.failed?'fail':'pass')}>{coverage.failed?coverage.failed+' à vérifier':coverage.passed+' conformes'}</span><small>{coverage.na} non applicables{coverage.errors?` · ${coverage.errors} erreurs`:''}</small></td><td>{run.reviewSampled?'Échantillon à relire':'Contrôles automatiques'}<small>{run.voice??'—'}</small></td><td>{money(run.costEstimatedUsd)}<small>{run.costActualEur!=null?`Rapproché : ${new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(run.costActualEur)}`:run.costReconciledEur!=null?'Rapprochement incomplet':'Coût incomplet · réel non mesuré'}</small></td><td>{run.review?statuses[run.review]:run.flagged||run.reviewSampled?'À relire':'Non relue'}</td><td><button className="admin-button" onClick={()=>setSelected(run.id)}>Examiner <HomeIcon name="arrow" size={14}/></button></td></tr>;})}</tbody></table></div>}
        {data.nextCursor&&<button className="admin-button" disabled={busy} onClick={()=>void more()}>Voir les suivants</button>}</div>
    </>}
    <dialog ref={dialog} className="aiq-dialog" onClose={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget){const rect=e.currentTarget.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)e.currentTarget.close();}}}>
      <button className="admin-close aiq-close" type="button" aria-label="Fermer la relecture" onClick={()=>dialog.current?.close()}><HomeIcon name="close"/></button>
      {detailError?<p role="alert">{detailError}</p>:!detail?<p role="status">Chargement de la génération…</p>:<>
        <span className="admin-eyebrow">RELECTURE IA</span><h2>{detail.run.title}</h2><p>{date(detail.run.completedAt)} · {detail.run.durationSeconds??'—'} s · {detail.run.promptVersion??'—'}</p>
        <div className="aiq-detail-grid"><div>{detail.payload.mediaAvailable?<video controls playsInline preload="none" src={'/api/admin/jobs/'+encodeURIComponent(detail.run.jobId)+'/video?variant=master'}/>:<p>Vidéo indisponible. Les informations de génération restent consultables.</p>}
          <h3>Informations confirmées au départ</h3><dl className="admin-facts">{Object.entries(detail.payload.facts).map(([k,v])=><div key={k}><dt>{({locality:'Ville',transaction:'Transaction',propertyType:'Type',price:'Prix',area:'Surface',rooms:'Pièces'} as Record<string,string>)[k]??k}</dt><dd>{v===null?'Non renseigné':k==='price'?new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format((v as {amountCents:number}).amountCents/100):typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl>
          <p>Estimation connue : {money(detail.payload.costs.estimatedUsd)}. Coût facturé : {money(detail.payload.costs.actualUsd)}.</p>{detail.ledger.reconciledEur!==null&&<p>Coût rapproché dans Rentabilité : {new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(detail.ledger.reconciledEur)}{detail.ledger.actualEur===null?' · couverture incomplète':' · fournisseurs couverts'}</p>}<p className="aiq-muted">Non mesuré : {detail.payload.costs.unknownProviders.join(', ')}.</p>
          <a className="admin-button" href={detail.traceUrl} target="_blank" rel="noreferrer">Ouvrir la trace PostHog <HomeIcon name="arrow" size={15}/></a>
        </div><div><h3>Description source</h3><div className="aiq-text">{detail.payload.sourceText||'Description absente.'}</div><h3>Narration finale compilée</h3><div className="aiq-text">{detail.payload.finalNarration||'Narration non préparée.'}</div>
          <details><summary>Texte réellement envoyé à la voix et écoute</summary>{detail.payload.audio?.map((clip,i)=><div className="aiq-audio" key={clip.id}><strong>Passage {i+1} · {(clip.durationMs/1000).toFixed(1)} s</strong><audio controls preload="none" src={'/api/admin/ai-quality/'+encodeURIComponent(detail.run.id)+'/audio?clip='+i}/></div>)}{detail.payload.spokenText?.map((text,i)=><p className="aiq-text" key={i}>{text}</p>)}</details>
        </div></div>
        <h3>Résultats et motifs</h3><div className="aiq-check-grid">{detail.run.checks.map(c=><Check check={c} key={c.key}/>)}</div>
        <div className="aiq-review"><h3>Votre verdict</h3><label>Résultat<select value={verdict} onChange={e=>setVerdict(e.target.value as QualityVerdict)}><option value="problem">Problème confirmé</option><option value="false_positive">Faux positif</option><option value="intentional">Choix volontaire de l’utilisateur</option><option value="accepted">Contenu validé</option></select></label>
          <label>Note de relecture<textarea value={note} maxLength={1500} rows={3} onChange={e=>setNote(e.target.value)} placeholder="Décrivez le problème ou le motif de validation."/></label>
          <div className="aiq-actions"><button className="admin-button admin-button-primary" disabled={busy} onClick={()=>void action({action:'review',id:detail.run.id,verdict,note},'Relecture enregistrée.')}>Enregistrer le verdict</button><button className="admin-button" disabled={busy||!detail.run.review} onClick={()=>void action({action:'dataset',id:detail.run.id,label:detail.run.title},'Cas ajouté au jeu de référence.')}>Ajouter au jeu de référence</button></div>
          {!detail.run.review&&<small>Enregistrez d’abord un verdict avant d’ajouter ce cas au jeu de référence.</small>}{error&&<p role="alert" className="admin-error">{error}</p>}{notice&&<p role="status">{notice}</p>}</div>
      </>}
    </dialog>
  </section>;
}
