'use client';
import {useEffect,useState} from 'react';
import type {CommercialSummary} from '../lib/commercial';
const money=(n:unknown,currency='EUR')=>new Intl.NumberFormat('fr-FR',{style:'currency',currency}).format(Number(n??0)),n=(v:unknown)=>Number(v??0).toLocaleString('fr-FR');
export function AdminCommercial(){const [data,setData]=useState<CommercialSummary|null>(null),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();void fetch('/api/admin?section=commercial',{signal:c.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<CommercialSummary>;}).then(setData).catch(()=>{if(!c.signal.aborted)setError('Les données commerciales ne peuvent pas être chargées.');});return()=>c.abort();},[]);
 if(error)return <p role="alert" className="admin-error">{error}</p>;if(!data)return <p>Lecture des données commerciales…</p>;
 const live=data.revenue.find(r=>r.mode==='live'),test=data.revenue.find(r=>r.mode==='test'),reconciled=data.costs.filter(c=>c.currency==='EUR'&&(c.kind==='reconciled'||c.kind==='fixed')).reduce((s,c)=>s+Number(c.amountMicros??0)/1e6,0);
 const rows:[string,unknown][]=[['Paiements confirmés HT · réelles',money(Number(live?.revenueHtCents??0)/100)],['Agences ayant payé · réelles',n(live?.payingAgencies)],['Paiements confirmés · réelles',n(live?.invoices)],['Paiements Stripe de test · HT',money(Number(test?.revenueHtCents??0)/100)],['Animations réutilisées',n(data.animations?.reused)],['Nouvelles animations réussies',n(data.animations?.newReady)]];
 return <><p className="admin-muted">Les 30 derniers jours · événements enregistrés en UTC. Abonnements et recharges sont inclus, remboursements déduits. Les paiements de test sont exclus des recettes réelles.</p><div className="admin-metrics">{rows.map(([label,value])=><div className="admin-metric" key={label}><span>{label}</span><strong>{String(value)}</strong></div>)}</div>
 <div className="admin-dashboard-grid"><section className="admin-card"><h3>Parcours des essais anonymes</h3>{([['Lancements','requested'],['Vidéos terminées','ready'],['Terminées et récupérées après connexion','claimed'],['Terminées avec téléchargement enregistré','downloaded']] as const).map(([label,key])=><p className="admin-summary-lines" key={key}><span>{label}</span><strong>{n(data.trial?.[key])}</strong></p>)}<p className="admin-muted">Comptages par vidéo de la cohorte lancée sur la période. Une vidéo téléchargée peut aussi être récupérée : ces étapes ne s’additionnent pas.</p></section>
 <section className="admin-card"><h3>Nouveaux comptes</h3>{([['Inscriptions','signedUp'],['Comptes confirmés','verified'],['Avec au moins une vidéo terminée','createdVideo'],['Avec une facture réelle payée','paid']] as const).map(([label,key])=><p className="admin-summary-lines" key={key}><span>{label}</span><strong>{n(data.accounts?.[key])}</strong></p>)}<p className="admin-muted">Cohorte inscrite sur la période, suivie jusqu’à aujourd’hui. Le trafic HTML ne constitue pas un décompte de visiteurs uniques.</p></section>
 <section className="admin-card"><h3>Recettes et coûts connus</h3><p>Paiements confirmés HT : <strong>{money(Number(live?.revenueHtCents??0)/100)}</strong></p><p>Coûts EUR rapprochés et fixes : <strong>{money(reconciled)}</strong></p><p>Solde partiel : <strong>{money(Number(live?.revenueHtCents??0)/100-reconciled)}</strong></p><p className="admin-muted">Ce solde reste partiel. Retrouvez les frais Stripe et factures fournisseurs par vidéo dans l’onglet Rentabilité. Les provisions et achats de crédits ne sont pas additionnés aux coûts d’utilisation.</p>{data.costs.map((c,i)=><p key={i}>{c.kind} · {c.currency} : {money(Number(c.amountMicros)/1e6,String(c.currency))} ({n(c.events)} événements)</p>)}</section>
 <section className="admin-card"><h3>Suivi des animations</h3><p>{n(data.animations?.requested)} demandées · {n(data.animations?.reused)} réutilisées · {n(data.animations?.newReady)} nouvelles réussies.</p><p>{n(data.animations?.uncertain)} appel(s) fournisseur à rapprocher.</p><p className="admin-muted">Une réutilisation évite un nouvel appel Runway. Aucun montant de facture fournisseur n’est déduit de ce compteur.</p></section></div>
 <section className="admin-card admin-card-wide"><h3>Activité par agence</h3><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Agence</th><th>Membres</th><th>Dossiers</th><th>Vidéos terminées</th><th>Recettes réelles HT</th></tr></thead><tbody>{data.agencies.map(a=><tr key={String(a.id)}><td>{String(a.name)}</td><td>{n(a.members)}</td><td>{n(a.projects)}</td><td>{n(a.ready)}</td><td>{money(Number(a.revenueHtCents)/100)}</td></tr>)}</tbody></table></div><p className="admin-muted">100 premières agences, triées par recettes puis vidéos. Comptages des membres et dossiers actuels.</p></section></>;
}
