'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {creditPlans,PromotionSettings,promotionCredits,type PaidCreditPlanCode} from '@bienvu/contracts';

type Code=PromotionSettings&{id:string;version:number;reserved:number;redeemed:number;granted:number};
type Usage={id:string;agency:string;code:string;plan:string;bonus:number;state:string;at:string;paidAt:string|null;invoiceId:string|null;grossCents:number|null;refundedCents:number|null;disputed:number;reversed:number;reserved:number;consumed:number;expiresAt:string|null;sessionId:string|null};
type Report={mode:'test'|'live';billingMode:'test'|'live';codes:Code[];history:Usage[];nextCursor:string|null;audit:{id:string;actor:string;reason:string;at:string}[];totals?:{redeemed:number;granted:number;reserved:number;reversed:number}};
const plans=creditPlans.filter(p=>p.price>0),defaults=():PromotionSettings=>({code:'',name:'',active:false,startsAt:null,endsAt:null,maxRedemptions:null,plans:['solo','agence','equipe','reseau']});
const date=(value:string|null)=>value?new Date(value).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'}):'—';
const localDate=(value:string|null)=>{if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
function campaignStatus(p:Code){return !p.active?'Désactivé':p.startsAt&&Date.parse(p.startsAt)>Date.now()?'À venir':p.endsAt&&Date.parse(p.endsAt)<=Date.now()?'Expiré':p.maxRedemptions!==null&&p.reserved+p.redeemed>=p.maxRedemptions?'Limite atteinte':'Actif';}
export function AdminPromotions(){
  const [data,setData]=useState<Report|null>(null),[selected,setSelected]=useState<string|null>(null),[editing,setEditing]=useState<Code|null>(null),[form,setForm]=useState<PromotionSettings|null>(null);
  const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[mode,setMode]=useState<'test'|'live'|''>(''),[revision,setRevision]=useState(0),[reason,setReason]=useState('');
  const [busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const scope=useRef('');scope.current=[mode,search,status,selected].join(':');
  useEffect(()=>{const id=setTimeout(()=>setSearch(query.trim()),300);return()=>clearTimeout(id);},[query]);
  function endpoint(cursor?:string){const p=new URLSearchParams({q:search,status});if(mode)p.set('mode',mode);if(selected)p.set('id',selected);if(cursor)p.set('cursor',cursor);return '/api/admin/promotions?'+p;}
  useEffect(()=>{const c=new AbortController();setBusy(true);setError('');void fetch(endpoint(),{signal:c.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error(r.status===403?'Seul le superadmin peut gérer les codes bonus.':'Chargement interrompu. Réessayez.');return r.json() as Promise<Report>;}).then(v=>{if(!c.signal.aborted)setData(v);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[search,status,selected,mode,revision]);
  function edit(p:Code|null){setEditing(p);setForm(p?{code:p.code,name:p.name,active:p.active,startsAt:p.startsAt,endsAt:p.endsAt,maxRedemptions:p.maxRedemptions,plans:p.plans}:defaults());setReason('');setError('');if(p)setSelected(p.id);}
  async function post(body:unknown){const r=await fetch('/api/admin/promotions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error(r.status===409?'Ce code existe déjà ou a été modifié ailleurs. Actualisez avant de réessayer.':r.status===429?'Trop de modifications. Patientez une minute.':'Enregistrement refusé. Vérifiez les champs et votre accès.');return r.json() as Promise<{id?:string;checked?:number;released?:number}>;}
  async function save(e:FormEvent){e.preventDefault();if(!form||saving)return;const p=PromotionSettings.safeParse(form);if(!p.success){setError(p.error.issues[0].message);return;}setSaving(true);setError('');try{const saved=await post({action:'save',...(editing?{id:editing.id,version:editing.version}:{}),settings:p.data,reason});setForm(null);setEditing(null);setSelected(saved.id!);setNotice('Campagne enregistrée. Les paiements déjà préparés conservent leur bonus.');setRevision(n=>n+1);}catch(e){setError(e instanceof Error?e.message:'Enregistrement interrompu.');}finally{setSaving(false);}}
  async function reconcile(){if(saving)return;setSaving(true);setError('');try{const r=await post({action:'reconcile'});setNotice(`${r.checked} paiement(s) vérifié(s) auprès de Stripe ; ${r.released} réservation(s) expirée(s) libérée(s).`);setRevision(n=>n+1);}catch(e){setError(e instanceof Error?e.message:'Vérification interrompue.');}finally{setSaving(false);}}
  async function more(){if(!data?.nextCursor||busy)return;const currentScope=scope.current;setBusy(true);try{const r=await fetch(endpoint(data.nextCursor),{cache:'no-store'});if(!r.ok)throw Error();const next=await r.json() as Report;if(scope.current===currentScope)setData(current=>current?{...next,history:[...current.history,...next.history]}:next);}catch{if(scope.current===currentScope)setError('La suite des utilisations est indisponible.');}finally{if(scope.current===currentScope)setBusy(false);}}
  function csv(){if(!data)return;const cell=(v:unknown)=>'"'+String(v??'').replace(/^[\s]*[=+\-@]/,"'$&").replaceAll('"','""')+'"';const rows=[['Agence','Code','Offre','État','Bonus','Utilisés','Repris','Date','Facture'],...data.history.map(r=>[r.agency,r.code,r.plan,r.state,r.bonus,r.consumed,r.reversed,r.at,r.invoiceId])];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`bienvu-code-bonus-${data.mode}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const total=data?.totals;
  return <div className="admin-promotions">
    <p className="admin-notice">+20 % de crédits après le premier paiement d’un nouvel abonnement, une seule fois par agence. Prix Stripe inchangé. Bonus valable pendant la première mensualité, sans report, consommé en priorité. Aucun bonus sur les recharges.</p>
    <div className="promo-admin-toolbar"><button className="admin-button" type="button" onClick={()=>edit(null)}>Créer un code</button><button className="admin-button" type="button" disabled={saving||!data||data.mode!==data.billingMode} onClick={()=>void reconcile()}>Vérifier les paiements expirés</button><label>Données de paiement<select value={mode||data?.mode||'test'} onChange={e=>{setMode(e.target.value as 'test'|'live');setSelected(null);}}><option value="test">Test</option><option value="live">Réel</option></select></label></div>
    <p className="admin-muted">Les limites d’utilisation et les statistiques sont séparées entre test et réel. Une place est réservée pendant le paiement ; elle est libérée uniquement après confirmation de son expiration par Stripe. Un paiement confirmé en attente de facture reste réservé.</p>
    {total&&<div className="promo-admin-stats"><div><strong>{total.redeemed}</strong><span>Bonus attribués</span></div><div><strong>{total.reserved}</strong><span>Paiements en attente</span></div><div><strong>{total.granted}</strong><span>Crédits offerts</span></div><div><strong>{total.reversed}</strong><span>Crédits repris</span></div></div>}
    {notice&&<p className="admin-notice" role="status">{notice}</p>}{error&&<p className="admin-error" role="alert">{error}</p>}
    {form&&<form className="promo-admin-form" onSubmit={save}><h3>{editing?'Modifier '+editing.code:'Nouvelle campagne'}</h3><div className="promo-admin-fields"><label>Code<input required minLength={3} maxLength={32} pattern="[A-Za-z0-9][A-Za-z0-9_-]{2,31}" value={form.code} disabled={Boolean(editing)} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></label><label>Nom de la campagne<input required minLength={3} maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Début (heure locale)<input type="datetime-local" value={localDate(form.startsAt)} onChange={e=>setForm({...form,startsAt:e.target.value?new Date(e.target.value).toISOString():null})}/></label><label>Fin (heure locale)<input type="datetime-local" value={localDate(form.endsAt)} onChange={e=>setForm({...form,endsAt:e.target.value?new Date(e.target.value).toISOString():null})}/></label><label>Utilisations maximales<input type="number" min={1} max={100000} step={1} placeholder="Sans limite" value={form.maxRedemptions??''} onChange={e=>setForm({...form,maxRedemptions:e.target.value?Number(e.target.value):null})}/></label><label className="promo-admin-checkbox"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Activer ce code</label></div><fieldset><legend>Offres éligibles · bonus de 20 %</legend><div className="promo-admin-plans">{plans.map(p=><label key={p.code}><input type="checkbox" checked={form.plans.includes(p.code as PaidCreditPlanCode)} onChange={e=>setForm({...form,plans:e.target.checked?[...form.plans,p.code as PaidCreditPlanCode]:form.plans.filter(v=>v!==p.code)})}/>{p.name}<small>{p.credits} + {promotionCredits(p.code as PaidCreditPlanCode)} = {p.credits+promotionCredits(p.code as PaidCreditPlanCode)} crédits la première mensualité</small></label>)}</div></fieldset><label>Motif de la modification<input required minLength={5} maxLength={300} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex. campagne de lancement auprès des agences"/></label><div className="promo-admin-toolbar"><button className="admin-button" disabled={saving||!form.plans.length} type="submit">{saving?'Enregistrement…':'Enregistrer la campagne'}</button><button className="admin-button" type="button" disabled={saving} onClick={()=>setForm(null)}>Annuler</button></div></form>}
    <div className="promo-admin-toolbar"><label>Rechercher un code ou une campagne<input type="search" value={query} onChange={e=>setQuery(e.target.value)} maxLength={100}/></label><label>Activation<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tous</option><option value="active">Activés</option><option value="inactive">Désactivés</option></select></label></div>
    {busy&&!data?<p role="status">Chargement des campagnes…</p>:<div className="promo-admin-table"><table><thead><tr><th>Campagne</th><th>État</th><th>Offres</th><th>Période</th><th>Utilisations</th><th>Crédits offerts</th><th>Actions</th></tr></thead><tbody>{data?.codes.map(p=><tr key={p.id}><th scope="row"><strong>{p.code}</strong><small>{p.name}</small></th><td>{campaignStatus(p)}</td><td>{p.plans.map(code=>plans.find(v=>v.code===code)?.name).join(', ')}</td><td>{p.startsAt?date(p.startsAt):'Dès activation'}<small>{p.endsAt?'Jusqu’au '+date(p.endsAt):'Sans date de fin'}</small></td><td>{p.redeemed} attribué(s)<small>{p.reserved} en attente · {p.maxRedemptions??'sans limite'}</small></td><td>{p.granted}</td><td><div className="promo-admin-row-actions"><button className="admin-button" type="button" onClick={()=>edit(p)}>Modifier</button><button className="admin-button" type="button" aria-pressed={selected===p.id} onClick={()=>{setSelected(p.id);setForm(null);}}>Utilisations</button><button className="admin-button" type="button" onClick={()=>void navigator.clipboard.writeText(p.code).then(()=>setNotice('Code copié.')).catch(()=>setError('Copie indisponible. Sélectionnez le code pour le copier.'))}>Copier</button></div></td></tr>)}</tbody></table>{data&&!data.codes.length&&<p>Aucune campagne. Créez votre premier code bonus.</p>}{data?.codes.length===200&&<p>200 campagnes affichées. Affinez votre recherche.</p>}</div>}
    {selected&&<section className="promo-admin-history"><div className="promo-admin-toolbar"><h3>Utilisations · {data?.codes.find(p=>p.id===selected)?.code??'Campagne'}</h3><button className="admin-button" type="button" onClick={csv} disabled={!data?.history.length}>Exporter les lignes affichées</button></div><div className="promo-admin-table"><table><thead><tr><th>Agence / offre</th><th>État</th><th>Crédits</th><th>Paiement</th><th>Validité du bonus</th></tr></thead><tbody>{data?.history.map(r=><tr key={r.id}><th scope="row">{r.agency}<small>{plans.find(p=>p.code===r.plan)?.name} · {date(r.at)}</small></th><td>{r.state==='redeemed'?'Attribué':r.state==='released'?'Paiement expiré':'Paiement en attente'}{Boolean(r.disputed)&&<small>Litige · crédits suspendus</small>}{r.state==='reserved'&&!r.sessionId&&<small>Création de paiement à confirmer</small>}</td><td>+{r.bonus}<small>{r.consumed} utilisés · {r.reserved} réservés · {r.reversed} repris</small></td><td>{r.invoiceId??'—'}<small>{r.grossCents!==null?new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(r.grossCents/100):'Sans paiement confirmé'}{r.refundedCents?' · remboursement '+(r.refundedCents/100)+' €':''}</small></td><td>{date(r.expiresAt)}{r.expiresAt&&Date.parse(r.expiresAt)<=Date.now()&&<small>Bonus expiré</small>}</td></tr>)}</tbody></table>{!data?.history.length&&<p>Aucune utilisation dans ce mode.</p>}</div>{data?.nextCursor&&<button className="admin-button" type="button" disabled={busy} onClick={()=>void more()}>Voir la suite</button>}<h3>Journal de la campagne</h3><ul className="promo-admin-audit">{data?.audit.map(a=><li key={a.id}><strong>{date(a.at)} · {a.actor}</strong><span>{a.reason}</span></li>)}</ul></section>}
  </div>;
}
