'use client';
import {useEffect,useRef,useState} from 'react';
import {editorResponse} from '../lib/editor-client';
type View={title:string;hash:string;status:string;expiresAt:string;videoUrl:string;comments:{name:string;text:string;time:number|null;at:string}[]};
export function ClientReview({token}:{token:string}){
 const [view,setView]=useState<View|null>(null),[name,setName]=useState(''),[text,setText]=useState(''),[time,setTime]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),video=useRef<HTMLVideoElement>(null);
 useEffect(()=>{const controller=new AbortController();void fetch(`/api/validation/${token}`,{signal:controller.signal}).then(r=>editorResponse<View>(r)).then(setView).catch(()=>setError('Ce lien n’est plus disponible. Demandez une nouvelle version à votre agence.'));return()=>controller.abort();},[token]);
 async function reply(action:'comment'|'approve'){if(!view)return;setBusy(true);setError('');try{const value=await editorResponse<View>(await fetch(`/api/validation/${token}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,name,text,time,hash:view.hash})}));setView(value);setText('');}catch(e){setError(e instanceof Error?e.message:'Votre réponse n’a pas pu être enregistrée.');}finally{setBusy(false);}}
 return <main className="client-review"><a href="/" className="client-review-brand">bienvu</a><p className="workspace-eyebrow">VALIDATION PRIVÉE</p><h1>{view?.title??'Votre vidéo'}</h1>{error&&<p role="alert" className="workspace-error">{error}</p>}{view&&<><video ref={video} src={view.videoUrl} controls playsInline preload="metadata" onTimeUpdate={()=>setTime(Number((video.current?.currentTime??0).toFixed(1)))}/><p>Version {view.hash.slice(0,8)} · {view.status==='approved'?'Validée':`Lien valable jusqu’au ${new Date(view.expiresAt).toLocaleDateString('fr-FR')}`}</p>{view.status!=='approved'&&<form onSubmit={e=>{e.preventDefault();void reply('comment');}}><label>Votre nom<input value={name} maxLength={80} required onChange={e=>setName(e.target.value)}/></label><label>Votre commentaire à {time.toFixed(1)} s<textarea value={text} maxLength={1500} onChange={e=>setText(e.target.value)} rows={4}/></label><div><button disabled={busy||!name.trim()||!text.trim()}>Envoyer le commentaire</button><button disabled={busy||!name.trim()} type="button" onClick={()=>void reply('approve')}>Valider cette version</button></div></form>}{view.comments.map((c,i)=><blockquote key={i}><strong>{c.name}{c.time!==null?` · ${c.time.toFixed(1)} s`:''}</strong><p>{c.text}</p></blockquote>)}</>}</main>;
}
