'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {creditPacks,type CreditPackCode} from '@bienvu/contracts';
import {useAccount} from './account';
import {HomeIcon} from './home-icons';
type Purchase={id:string;credits:number;priceCents:number;mode:string;at:string;remaining:number;reversed:number;disputed:number;validUntil:string};
export function CreditTopups({enabled,mode,validDays=0}:{enabled:boolean;mode:'test'|'live'|null;validDays?:number}){
 const {me,refreshRights}=useAccount(),identity=me?.agency.id,owner=useRef(identity);owner.current=identity;
 const [chosen,setChosen]=useState<CreditPackCode|null>(null),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[purchases,setPurchases]=useState<Purchase[]|null>(null),[revision,setRevision]=useState(0),[confirmation,setConfirmation]=useState(false);
 useEffect(()=>{setChosen(null);setAccepted(false);setBusy(false);setError('');setPurchases(null);const confirmed=new URLSearchParams(location.search).get('recharge')==='confirmation';setConfirmation(confirmed);if(confirmed&&identity)for(const p of creditPacks)sessionStorage.removeItem(`bienvu:topup:${mode}:${identity}:${p.code}`);if(!identity)return;const c=new AbortController();void fetch('/api/billing/topups',{signal:c.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<{purchases:Purchase[]}>;}).then(b=>{if(!c.signal.aborted)setPurchases(b.purchases);}).catch(()=>{if(!c.signal.aborted)setError('L’historique des recharges est momentanément indisponible.');});return()=>c.abort();},[identity,revision]);
 async function buy(){if(busy||!me||!chosen||!accepted)return;setBusy(true);setError('');const agency=identity;
  try{const storage=`bienvu:topup:${mode}:${agency}:${chosen}`,saved=sessionStorage.getItem(storage);let key:{id:string;expires:number}|null=null;try{key=saved?JSON.parse(saved):null;}catch{}if(!key||key.expires<=Date.now()){key={id:crypto.randomUUID(),expires:Date.now()+44*60000};sessionStorage.setItem(storage,JSON.stringify(key));}
   const r=await fetch('/api/billing/topups',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key.id},body:JSON.stringify({pack:chosen,accepted:true})}),b=await r.json() as {url?:string};
   if(owner.current!==agency)return;if(!r.ok||!b.url)throw Error(r.status===409?'Une recharge est déjà en cours. Reprenez le même pack ou attendez l’expiration du paiement.':'Impossible d’ouvrir le paiement. Votre solde reste disponible.');
   const url=new URL(b.url);if(url.hostname!=='checkout.stripe.com'||url.protocol!=='https:')throw Error('Lien de paiement indisponible.');location.assign(url.href);
  }catch(e){if(owner.current===agency){setError(e instanceof Error?e.message:'Paiement indisponible.');setBusy(false);}}
 }
 const pack=creditPacks.find(p=>p.code===chosen),manages=me&&['owner','admin'].includes(me.role??'owner');
 return <section className="offers-topups" id="recharges"><div className="offers-topups-heading"><div><p className="offers-kicker">UN BESOIN PONCTUEL ?</p><h2>Quelques crédits de plus.</h2><p>Une recharge, sans modifier votre abonnement. {validDays?'Valable 12 mois.':'Sans expiration.'}</p></div><span>Crédits mensuels utilisés en premier</span></div>
  <div className="offers-topup-cards">{creditPacks.map(p=><article key={p.code}><h3>{p.credits} crédits</h3><p className="offers-topup-price"><strong>{p.priceCents/100} €</strong><span>HT · achat unique</span></p><p>{(p.priceCents/p.credits/100).toLocaleString('fr-FR',{style:'currency',currency:'EUR'})} HT par crédit</p><button type="button" className="offers-action offers-action-outline" disabled={Boolean(me)&&(!enabled||!manages)||busy} onClick={()=>{if(!me){location.assign('/connexion?next=/abonnement');return;}setChosen(p.code);setAccepted(false);setError('');}}>Choisir ce pack<HomeIcon name="arrow" size={17}/></button></article>)}</div>
  {me&&!manages&&<p>Seuls le propriétaire et les administrateurs de l’agence peuvent acheter des crédits.</p>}
  {confirmation&&<p className="offers-billing-notice" role="status">Votre recharge apparaîtra dès que Stripe aura confirmé le paiement. <button type="button" onClick={()=>{void refreshRights();setRevision(n=>n+1);}}>Actualiser mon solde</button></p>}
  {error&&<p className="offers-billing-notice" role="alert">{error}</p>}
  {pack&&<section className="offers-checkout-confirm" aria-label="Confirmer la recharge"><h3>Recharge de {pack.credits} crédits</h3><p>{pack.priceCents/100} € HT · un seul paiement · {validDays?'valable 12 mois':'sans expiration'}. Votre abonnement reste inchangé.</p><label><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>J’accepte les <Link href="/conditions">conditions d’utilisation</Link> et j’ai lu la <Link href="/confidentialite">politique de confidentialité</Link>.</label><div><button type="button" disabled={busy} onClick={()=>setChosen(null)}>Annuler</button><button type="button" disabled={!accepted||busy} onClick={()=>void buy()}>{busy?'Ouverture…':'Continuer vers Stripe'}</button></div></section>}
  {purchases&&purchases.length>0&&<details className="offers-topup-history"><summary>Mes recharges · {purchases.length}</summary><div className="offers-table-scroll"><table><thead><tr><th>Date</th><th>Pack</th><th>Montant HT</th><th>Crédits restants</th><th>Validité</th></tr></thead><tbody>{purchases.map(p=><tr key={p.id}><td>{new Date(p.at).toLocaleDateString('fr-FR')}</td><td>{p.credits} crédits {p.mode==='test'&&<small>Test</small>}</td><td>{(p.priceCents/100).toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}</td><td>{p.disputed?'En attente · litige':p.remaining}{p.reversed>0&&<small>{p.reversed} crédit(s) annulé(s) après remboursement</small>}</td><td>{p.validUntil.startsWith('9999')?'Sans expiration':new Date(p.validUntil).toLocaleDateString('fr-FR')}</td></tr>)}</tbody></table></div><p>Les 50 dernières recharges. Les crédits réservés par une génération sont déjà retirés du solde disponible.</p></details>}
 </section>;
}
