'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {creditPlans,CreditHistory} from '@bienvu/contracts';
import {useAccount} from './account';
import {HomeIcon} from './home-icons';
import {CreditTopups} from './credit-topups';
type Billing={enabled:boolean;mode:'test'|'live'|null;topupValidDays?:number;subscription:{plan:string;status:string;cancelAtPeriodEnd:number;periodEnd:string;mode:string}|null};
const benefits=['Import par lien ou saisie manuelle','Voix et sous-titres au choix','Formats vertical et horizontal','Téléchargement sans filigrane après connexion','Logo et couleurs de votre agence','Runway au choix : + 1 crédit par photo'];
export function Offers(){
  const {me}=useAccount();const owner=useRef(me?.agency.id);owner.current=me?.agency.id;
  const [photos,setPhotos]=useState(0),[history,setHistory]=useState<CreditHistory|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [billing,setBilling]=useState<Billing|null>(null),[chosen,setChosen]=useState<'plus'|'pro'|null>(null),[accepted,setAccepted]=useState(false),[paymentBusy,setPaymentBusy]=useState(false),[paymentError,setPaymentError]=useState(''),[confirmation,setConfirmation]=useState(false);
  useEffect(()=>{setBilling(null);if(!me)return;const c=new AbortController();setConfirmation(new URLSearchParams(location.search).get('paiement')==='confirmation');void fetch('/api/billing',{signal:c.signal}).then(r=>r.ok?r.json() as Promise<Billing>:null).then(setBilling).catch(()=>{});return()=>c.abort();},[me?.agency.id]);
  async function payment(portal=false){if(paymentBusy||!me)return;setPaymentBusy(true);setPaymentError('');try{
    const storageKey=`bienvu:checkout:${billing?.mode}:${me.agency.id}:${chosen}`,stored=sessionStorage.getItem(storageKey);let key=stored?JSON.parse(stored):null;
    if(!key||key.expires<Date.now()){key={id:crypto.randomUUID(),expires:Date.now()+25*60000};sessionStorage.setItem(storageKey,JSON.stringify(key));}
    const r=await fetch('/api/billing/'+(portal?'portal':'checkout'),{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key.id},body:JSON.stringify(portal?{}:{plan:chosen,accepted})});
    const b=await r.json() as {url?:string};if(!r.ok||!b.url)throw Error(r.status===409?'Un abonnement ou une demande de paiement est déjà en cours. Actualisez cette page.':'Le paiement est momentanément indisponible. Aucun crédit n’a été débité.');
    location.assign(b.url);
  }catch(e){setPaymentError(e instanceof Error?e.message:'Paiement indisponible.');setPaymentBusy(false);}}
  const manages=me&&['owner','admin'].includes(me.role??'owner'),hasSubscription=billing?.subscription&&billing.subscription.mode===billing.mode&&!['canceled','incomplete_expired'].includes(billing.subscription.status);
  useEffect(()=>{setHistory(null);setError('');if(!me)return;const controller=new AbortController();
    void fetch('/api/credits',{cache:'no-store',signal:controller.signal}).then(async response=>{
      if(!response.ok)throw Error();const data=CreditHistory.parse(await response.json());if(!controller.signal.aborted)setHistory(data);
    }).catch(()=>{if(!controller.signal.aborted)setError('Historique momentanément indisponible.');});return()=>controller.abort();
  },[me?.agency.id,me?.rights.developmentRemaining,me?.rights.creditReserved]);
  async function more(){if(!history?.nextCursor||busy)return;setBusy(true);const agency=owner.current;
    try{const response=await fetch('/api/credits?cursor='+encodeURIComponent(history.nextCursor),{cache:'no-store'});if(!response.ok)throw Error();
      const data=CreditHistory.parse(await response.json());if(owner.current===agency)setHistory(current=>current?{...data,entries:[...current.entries,...data.entries]}:data);
    }catch{if(owner.current===agency)setError('La suite de votre historique est momentanément indisponible.');}finally{setBusy(false);}}
  const cost=1+photos,date=(at:string)=>new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium'}).format(new Date(at));
  return <div className="offers-page"><Link className="offers-back" href="/">← Retour au studio</Link>
    <header className="offers-heading"><p className="offers-kicker">CRÉDITS & ABONNEMENTS</p><h1>Vos vidéos, <em>à votre rythme.</em></h1><p>Des crédits pour créer et donner vie à vos photos.</p><span>1 vidéo = 1 crédit · 1 photo animée avec Runway = 1 crédit supplémentaire</span></header>
    {billing?.mode==='test'&&<p className="offers-billing-notice">Stripe en mode test : aucun encaissement réel. Utilisez uniquement les moyens de paiement de test.</p>}
    {confirmation&&<p role="status" className="offers-billing-notice">Votre paiement est en cours de confirmation. Les crédits apparaîtront après validation de la facture par Stripe. <button type="button" onClick={()=>location.reload()}>Actualiser</button></p>}
    {hasSubscription&&manages&&<button type="button" className="offers-action offers-action-outline" disabled={paymentBusy} onClick={()=>void payment(true)}>Gérer mon abonnement et mes factures →</button>}
    {paymentError&&<p role="alert" className="offers-billing-notice">{paymentError}</p>}
    {me&&<section className="offers-wallet" aria-label="Vos crédits"><div><h2>Vos crédits</h2><strong>{me.rights.developmentRemaining}</strong> disponibles</div><div>{me.rights.creditReserved} réservé(s) · {me.rights.creditConsumed} utilisé(s)<p>{me.rights.creditMonthly??me.rights.developmentRemaining} mensuels · {me.rights.creditPurchased??0} en recharge</p><p>{me.rights.renewalAt?'Crédits mensuels renouvelés le '+date(me.rights.renewalAt)+' · sans report':'Recharges conservées'}</p></div><a href="#credit-history">Voir mon historique ↓</a></section>}
    <section className="offers-calculator" aria-label="Calcul du coût"><div><h2>Combien coûte votre vidéo ?</h2><p>Les zooms, translations, la voix et les sous-titres sont inclus.</p></div><label>Photos animées avec Runway <select aria-label="Nombre de photos animées" value={photos} onChange={e=>setPhotos(Number(e.target.value))}>{Array.from({length:13},(_,n)=><option key={n} value={n}>{n} photo{n>1?'s':''}</option>)}</select></label><p className="offers-calculated-cost" role="status"><strong>{cost} crédit{cost>1?'s':''}</strong><span>1 vidéo + {photos} animation(s)</span></p></section>
    <div className="offers-cards">{creditPlans.map(plan=><section className={'offers-card offers-card-'+plan.code} key={plan.code} aria-labelledby={'offers-'+plan.code}>{plan.code==='plus'&&<span className="offers-recommended">Recommandé</span>}<h2 id={'offers-'+plan.code}>{plan.name}</h2><p className="offers-card-description">{plan.description}</p><div className="offers-price"><strong>{plan.price} €</strong><span>{plan.price?'HT / mois':'/ mois'}</span></div><p className="offers-quota"><strong>{plan.credits} crédits par mois</strong></p><p className="offers-equivalent" aria-live="polite">{Math.floor(plan.credits/cost)>0?'Jusqu’à '+Math.floor(plan.credits/cost)+' vidéo(s) avec '+photos+' photo(s) animée(s)':'Réduisez les animations pour cette offre.'}</p>
      {plan.code==='gratuit'?me?.rights.creditKind==='free'?<span className="offers-action offers-action-current">Votre offre actuelle</span>:<Link className="offers-action offers-action-outline" href={me?'/':'/connexion'}>{me?'Créer ma vidéo':'Obtenir mes crédits'}<HomeIcon name="arrow" size={17}/></Link>:<button className={'offers-action '+(plan.code==='plus'?'offers-action-primary':'offers-action-outline')} type="button" disabled={Boolean(me)&&(!billing?.enabled||!manages)||paymentBusy} onClick={()=>{if(!me){location.assign('/connexion?next=/abonnement');return;}if(hasSubscription){void payment(true);return;}setChosen(plan.code as 'plus'|'pro');setAccepted(false);}}>{hasSubscription&&billing?.subscription?.plan===plan.code?'Gérer mon offre':'Passer à '+plan.name}<HomeIcon name="arrow" size={17}/></button>}
      <ul className="offers-benefits">{benefits.map(benefit=><li key={benefit}><span aria-hidden="true">✓</span>{benefit}</li>)}</ul></section>)}</div><p className="offers-rollover">Crédits renouvelés chaque mois, sans cumul. Résiliation depuis votre abonnement, à la fin de la période payée.</p>
    {chosen&&<section className="offers-checkout-confirm" aria-label="Confirmer l’abonnement"><h2>BienVu {chosen==='plus'?'Plus':'Pro'}</h2><p>{chosen==='plus'?'19 € HT · 40':'49 € HT · 120'} crédits par mois, renouvellement automatique, sans report des crédits. Résiliation à la fin de la période payée.</p><label><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>J’accepte les <Link href="/conditions">conditions d’utilisation</Link> et j’ai lu la <Link href="/confidentialite">politique de confidentialité</Link>.</label><div><button type="button" disabled={paymentBusy} onClick={()=>setChosen(null)}>Annuler</button><button type="button" disabled={!accepted||paymentBusy} onClick={()=>void payment()}> {paymentBusy?'Ouverture…':'Continuer vers Stripe'}</button></div></section>}
    <CreditTopups enabled={billing?.enabled??false} mode={billing?.mode??null} validDays={billing?.topupValidDays}/>
    <section className="offers-trial-note"><strong>Essayez sans compte</strong><p>1 crédit offert pour une vidéo avec les mouvements classiques et un aperçu filigrané. Après connexion, récupérez-la sans filigrane : cet essai ne décompte pas vos 3 crédits mensuels.</p><Link href="/">Essayer gratuitement →</Link></section>
    <section className="offers-comparison"><h2>Comparez les offres</h2><div className="offers-table-scroll"><table><thead><tr><th scope="col">Fonctionnalités</th>{creditPlans.map(plan=><th key={plan.code} scope="col">{plan.name}</th>)}</tr></thead><tbody><tr><th scope="row">Crédits mensuels</th>{creditPlans.map(plan=><td key={plan.code}>{plan.credits}</td>)}</tr><tr><th scope="row">Coût d’une vidéo</th><td>1 crédit</td><td>1 crédit</td><td>1 crédit</td></tr><tr><th scope="row">Photo animée avec Runway</th><td>+ 1 crédit</td><td>+ 1 crédit</td><td>+ 1 crédit</td></tr><tr><th scope="row">Voix, sous-titres et mouvements classiques</th><td>Inclus</td><td>Inclus</td><td>Inclus</td></tr></tbody></table></div></section>
    {me&&<section className="offers-credit-history" id="credit-history"><h2>Historique de vos crédits</h2><p>Les crédits sont réservés au lancement. Les nouvelles animations réussies sont conservées 90 jours et débitées une seule fois, même si le montage échoue. Le crédit vidéo est restitué si l’export échoue.</p>{error&&<p role="alert">{error}</p>}{!history&&!error?<p>Chargement…</p>:history?.entries.length?<><div className="offers-table-scroll"><table><thead><tr><th scope="col">Création</th><th scope="col">État</th><th scope="col">Réservés</th><th scope="col">Utilisés</th><th scope="col">Restitués</th></tr></thead><tbody>{history.entries.map(entry=><tr key={entry.id}><th scope="row"><Link href={'/historique/'+entry.id}>{entry.title}</Link><small>{date(entry.at)}</small></th><td>{entry.gift?'Essai offert':entry.status==='ready'?'Terminée':entry.status==='failed'?'Échouée':'En préparation'}</td><td>{entry.reserved}</td><td>{entry.gift?'Offert':entry.used}</td><td>{entry.refunded}</td></tr>)}</tbody></table></div>{history.nextCursor&&<button className="offers-action offers-action-outline offers-history-more" type="button" disabled={busy} onClick={()=>void more()}>{busy?'Chargement…':'Voir la suite'}</button>}</>:history&&<p>Votre première création apparaîtra ici.</p>}</section>}
    <section className="offers-faq"><h2>Une question ?</h2><details><summary>Comment mes crédits sont-ils décomptés ?</summary><p>Une vidéo coûte 1 crédit pour 20, 30 ou 40 secondes. Chaque photo animée avec Runway ajoute 1 crédit. Le coût maximum est affiché avant le lancement. Télécharger ou revoir une vidéo ne coûte rien.</p></details><details><summary>Et si une création échoue ?</summary><p>Si l’export échoue, le crédit vidéo est restitué. Une animation échouée garde un mouvement classique et son supplément est restitué. Les animations réussies restent dans votre bibliothèque pendant 90 jours ; elles sont débitées une seule fois et réutilisables pour la même photo au même format.</p></details><details><summary>Les crédits gratuits se renouvellent-ils ?</summary><p>Un compte confirmé reçoit 3 crédits chaque mois à partir de son inscription, sans report. L’essai sans compte offre 1 crédit par visiteur. La vérification humaine et les limites du service restent applicables.</p></details><details><summary>Puis-je changer ou arrêter mon abonnement ?</summary><p>Gérez vos factures, votre moyen de paiement et votre résiliation depuis « Gérer mon abonnement ». La résiliation prend effet à la fin de la période déjà payée. Pour changer d’offre, contactez contact@bienvu.online.</p></details></section><footer className="offers-footer"><nav aria-label="Informations"><Link href="/conditions">Conditions</Link><Link href="/confidentialite">Confidentialité</Link><a href="mailto:contact@bienvu.online">Nous contacter</a></nav><span>{billing?.enabled?billing.mode==='test'?'Paiements de test':'Paiement sécurisé par Stripe':'Paiements en préparation'}</span></footer>
  </div>;
}
