'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {GenerationView,propertyFacts,propertyPrice,publicErrors,type PropertyDetail as Detail,type PublicErrorCode} from '@bienvu/contracts';
import {useAccount} from './account';
import {useGenerationStore} from './generation-store';
import {HomeIcon} from './home-icons';
import {SocialPublishDialog} from './social-publish-dialog';
import {ProblemReport} from './problem-report';
import {DraftActions} from './draft-actions';
import {propertyRequest,downloadBlob} from '../lib/property-client';
import {boundedDownload,propertyVisual,propertyZip} from '../lib/property-download';

type Tab='contents'|'photos'|'information'|'publications';
const statusLabel=(job:GenerationView)=>job.status==='ready'?job.videoUrl?'Prêt':'Indisponible':job.status==='failed'?'À reprendre':'En préparation';
const date=(value:string)=>new Date(value).toLocaleString('fr-FR',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
export function PropertyDetail({id}:{id:string}){
  const {me,loading}=useAccount(),store=useGenerationStore(),owner=me?.agency.id??'guest',scopeKey=`${owner}:${id}`,scope=useRef(scopeKey);scope.current=scopeKey;
  const [result,setResult]=useState<{scope:string;detail:Detail}|null>(null),[failure,setFailure]=useState(''),[revision,setRevision]=useState(0);
  const [tab,setTab]=useState<Tab>('contents'),[filter,setFilter]=useState('all'),[busy,setBusy]=useState<string|null>(null),[progress,setProgress]=useState('');
  const [preview,setPreview]=useState<GenerationView|null>(null),[confirm,setConfirm]=useState<GenerationView|null>(null),[social,setSocial]=useState<GenerationView|null>(null),[create,setCreate]=useState(false);
  const previewDialog=useRef<HTMLDialogElement>(null),shareDialog=useRef<HTMLDialogElement>(null),createDialog=useRef<HTMLDialogElement>(null),downloadAbort=useRef<AbortController|null>(null),editKey=useRef(crypto.randomUUID());
  const data=result?.scope===scopeKey?result.detail:null,property=data?.property;
  useEffect(()=>{setResult(null);setFailure('');setPreview(null);setConfirm(null);setSocial(null);setCreate(false);setBusy(null);setProgress('');setTab('contents');setFilter('all');editKey.current=crypto.randomUUID();
    if(loading||!me)return;const controller=new AbortController();
    void propertyRequest<Detail>(`/api/properties/${encodeURIComponent(id)}`,{signal:controller.signal}).then(detail=>{
      if(!controller.signal.aborted&&scope.current===scopeKey)setResult({scope:scopeKey,detail:{...detail,jobs:detail.jobs.map(j=>GenerationView.parse(j))}});
    }).catch(error=>{if(!controller.signal.aborted&&scope.current===scopeKey)setFailure(error.message);});
    return()=>{controller.abort();downloadAbort.current?.abort();};
  },[id,owner,loading,revision]);
  useEffect(()=>{if(!data)return;setResult(current=>current?.scope===scopeKey?{scope:scopeKey,detail:{...current.detail,jobs:current.detail.jobs.map(job=>store.jobs.find(j=>j.id===job.id)??job)}}:current);},[store.jobs,owner]);
  useEffect(()=>{const deleted=(event:Event)=>{if((event as CustomEvent<{agencyId:string}>).detail.agencyId===owner)setRevision(n=>n+1);};
    window.addEventListener('bienvu:draft-deleted',deleted);return()=>window.removeEventListener('bienvu:draft-deleted',deleted);},[owner]);
  useEffect(()=>{if(!preview)return;const trigger=document.activeElement as HTMLElement|null;previewDialog.current?.showModal();return()=>{previewDialog.current?.close();trigger?.focus();};},[preview]);
  useEffect(()=>{if(!confirm)return;const trigger=document.activeElement as HTMLElement|null;shareDialog.current?.showModal();return()=>{shareDialog.current?.close();trigger?.focus();};},[confirm]);
  useEffect(()=>{if(!create)return;const trigger=document.activeElement as HTMLElement|null;createDialog.current?.showModal();return()=>{createDialog.current?.close();trigger?.focus();};},[create]);
  async function more(){if(!data?.nextCursor||busy)return;setBusy('more');setFailure('');try{
    const next=await propertyRequest<Detail>(`/api/properties/${encodeURIComponent(id)}?cursor=${encodeURIComponent(data.nextCursor)}`);
    if(scope.current!==scopeKey)return;setResult(old=>old?.scope===scopeKey?{scope:scopeKey,detail:{...next,jobs:[...old.detail.jobs,...next.jobs.filter(j=>!old.detail.jobs.some(v=>v.id===j.id))].map(j=>GenerationView.parse(j))}}:old);
  }catch(error){report(error);}finally{if(scope.current===scopeKey)setBusy(null);}}
  function report(error:unknown){if(scope.current===scopeKey)setFailure(error instanceof Error?error.message:'Cette action n’a pas abouti.');}
  async function prepare(destination:'edit'|'create'){if(busy||!property)return;setBusy(destination);setFailure('');
    try{const value=await propertyRequest<{draftId:string}>(`/api/properties/${encodeURIComponent(id)}`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':editKey.current},body:JSON.stringify({action:'edit'})});
      if(scope.current===scopeKey)window.location.assign(destination==='edit'?`/?draft=${encodeURIComponent(value.draftId)}&fiche=1`:`/editeur?draft=${encodeURIComponent(value.draftId)}`);
    }catch(error){report(error);if(scope.current===scopeKey)setBusy(null);}}
  async function sharing(job:GenerationView,remove=false){if(busy)return;setBusy(job.id);setConfirm(null);setFailure('');
    try{const shared=await propertyRequest<{id:string}>(`/api/generations/${job.id}/share`,{method:remove?'DELETE':'POST'});
      if(scope.current!==scopeKey)return;setResult(old=>old?.scope===scopeKey?{scope:scopeKey,detail:{...old.detail,shares:remove?old.detail.shares.filter(s=>s.jobId!==job.id):[...old.detail.shares.filter(s=>s.jobId!==job.id),{id:shared.id,jobId:job.id}]}}:old);
    }catch(error){report(error);}finally{if(scope.current===scopeKey)setBusy(null);}}
  async function retry(job:GenerationView){if(busy)return;setBusy(job.id);setFailure('');try{await propertyRequest(`/api/generations/${job.id}/retry`,{method:'POST'});if(scope.current===scopeKey){await store.refresh();setRevision(n=>n+1);}}
    catch(error){report(error);}finally{if(scope.current===scopeKey)setBusy(null);}}
  async function visual(){if(!property||busy)return;setBusy('visual');setFailure('');try{const blob=await propertyVisual(property);if(scope.current===scopeKey)downloadBlob(blob,`bienvu-${property.reference}-visuel.png`);}catch(error){report(error);}finally{if(scope.current===scopeKey)setBusy(null);}}
  async function copy(){if(!data)return;setFailure('');try{await navigator.clipboard.writeText(data.caption);if(scope.current===scopeKey)setProgress('Texte copié.');}catch{report(new Error('La copie est indisponible. Sélectionnez le texte ou téléchargez-le.'));}}
  async function downloadAll(){if(!data||busy)return;setBusy('download');setFailure('');const controller=new AbortController();downloadAbort.current=controller;
    try{let jobs=[...data.jobs],cursor=data.nextCursor;while(cursor){const next=await propertyRequest<Detail>(`/api/properties/${encodeURIComponent(id)}?cursor=${encodeURIComponent(cursor)}`,{signal:controller.signal});jobs.push(...next.jobs);cursor=next.nextCursor;}
      const files:{name:string;bytes:Uint8Array}[]=[],ready=jobs.filter(j=>j.downloadUrl);let total=0;
      for(const [index,job]of ready.entries()){if(scope.current!==scopeKey||controller.signal.aborted)return;setProgress(`Préparation des vidéos : ${index+1} / ${ready.length}`);
        const bytes=await boundedDownload(job.downloadUrl!,200*1024*1024-total,controller.signal);total+=bytes.length;
        files.push({name:`${String(index+1).padStart(2,'0')}-video-${job.aspectRatio==='16:9'?'horizontale':'verticale'}-${job.id.slice(0,8)}.mp4`,bytes});}
      if(data.property.visualCount){const blob=await propertyVisual(data.property);files.push({name:'visuel-prix-surface.png',bytes:new Uint8Array(await blob.arrayBuffer())});}
      if(data.property.textCount)files.push({name:'texte-de-publication.txt',bytes:new TextEncoder().encode(data.caption)});
      if(!files.length)throw new Error('Aucun contenu n’est prêt au téléchargement.');
      if(scope.current===scopeKey&&!controller.signal.aborted){downloadBlob(propertyZip(files),`bienvu-${data.property.reference}.zip`);setProgress(`${files.length} contenu${files.length>1?'s':''} téléchargé${files.length>1?'s':''}.`);}
    }catch(error){if(!controller.signal.aborted)report(error);}finally{if(scope.current===scopeKey)setBusy(null);if(downloadAbort.current===controller)downloadAbort.current=null;}}
  if(loading)return <p className="property-notice" role="status">Chargement de votre espace…</p>;
  if(!me)return <section className="property-empty"><HomeIcon name="house" size={36}/><h1>Retrouvez tous les contenus de votre bien.</h1><p>Connectez-vous pour ouvrir cette fiche dans votre espace privé.</p><Link className="property-primary" href={`/connexion?next=${encodeURIComponent(`/biens/${id}`)}`}>Se connecter <HomeIcon name="arrow" size={18}/></Link><Link href="/biens">Retour à Mes biens</Link></section>;
  if(!data||!property)return <section className="property-detail"><Link className="property-breadcrumb" href="/biens">← Mes biens</Link>{failure?<p className="property-feedback" role="alert">{failure} <button type="button" onClick={()=>setRevision(n=>n+1)}>Réessayer</button></p>:<p className="property-notice" role="status">Chargement du bien…</p>}</section>;
  const titleCount=property.videoCount+property.draftCount+property.visualCount+property.textCount,canEdit=me.role!=='viewer',allPrivate=data.shares.length===0;
  return <section className="property-detail" aria-labelledby="property-title"><nav className="property-breadcrumb" aria-label="Fil d’Ariane"><Link href="/biens">Mes biens</Link><span aria-hidden="true">›</span><span>{property.title}</span></nav>
    <header className="property-detail-heading"><div className="property-detail-cover">{property.coverUrl?<img src={property.coverUrl} alt={`Photo de ${property.title}`}/>:<HomeIcon name="house" size={42}/>}</div>
      <div className="property-detail-intro"><h1 id="property-title">{property.title}</h1><div className="property-detail-reference"><span className={`property-badge${property.fields.transaction==='rent'?' is-rent':''}`}>{property.archived?'Archivé':property.fields.transaction==='rent'?'À louer':property.fields.transaction==='sale'?'À vendre':'À compléter'}</span><span>Réf. {property.reference}</span></div>
        <p>{propertyFacts(property.fields)||'Informations à compléter'}</p>{propertyPrice(property.fields)&&<strong>{propertyPrice(property.fields)}</strong>}</div>
      {canEdit&&<div className="property-detail-actions"><button className="property-button" type="button" disabled={Boolean(busy)} onClick={()=>void prepare('edit')}><HomeIcon name="pencil" size={18}/>{busy==='edit'?'Ouverture…':'Modifier le bien'}</button><button type="button" className="property-primary" disabled={Boolean(busy)} onClick={()=>setCreate(true)}><HomeIcon name="plus" size={20}/>Créer un contenu</button></div>}</header>
    <div className="property-tabs" role="tablist" aria-label="Rubriques du bien">{([['contents',`Contenus (${titleCount})`],['photos',`Photos (${property.photoCount})`],['information','Informations'],['publications',`Publications${data.publications.length?` (${data.publications.length})`:''}`]] as [Tab,string][]).map(([value,label])=>
      <button key={value} id={`property-tab-${value}`} role="tab" aria-selected={tab===value} aria-controls={`property-panel-${value}`} type="button" onClick={()=>setTab(value)} onKeyDown={event=>{
        const tabs:Tab[]=['contents','photos','information','publications'],i=tabs.indexOf(value),next=event.key==='ArrowRight'?tabs[(i+1)%4]:event.key==='ArrowLeft'?tabs[(i+3)%4]:event.key==='Home'?tabs[0]:event.key==='End'?tabs[3]:null;
        if(next){event.preventDefault();setTab(next);document.getElementById(`property-tab-${next}`)?.focus();}}} tabIndex={tab===value?0:-1}>{label}</button>)}</div>
    {failure&&<p className="property-feedback" role="alert">{failure}</p>}{progress&&<p className="property-download-status" role="status">{progress}</p>}
    <div role="tabpanel" id={`property-panel-${tab}`} aria-labelledby={`property-tab-${tab}`}>
    {tab==='contents'&&<><div className="property-content-toolbar"><div className="property-filters" role="group" aria-label="Filtrer les contenus">{([['all','Tous'],['videos','Vidéos'],['visuals','Visuels'],['texts','Textes']] as const).map(([value,label])=><button key={value} type="button" aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}</div>
      <div className="property-content-tools"><button type="button" className="property-button" disabled={Boolean(busy)||!titleCount} onClick={()=>void downloadAll()}><HomeIcon name="download" size={18}/>{busy==='download'?'Préparation…':'Tout télécharger'}</button><span><HomeIcon name={allPrivate?'lock':'globe'} size={17}/>{allPrivate?'Privés':'Privés et publiés'}</span></div></div>
      <div className="property-content-grid">
        {(filter==='all'||filter==='videos')&&data.jobs.map((job,index)=>{const shared=data.shares.find(s=>s.jobId===job.id),ready=job.status==='ready',label=job.aspectRatio==='16:9'?'Vidéo horizontale':`Vidéo verticale${property.videoCount>1?` · ${index+1}`:''}`;
          return <article className={`property-content-card${job.aspectRatio==='16:9'?' is-landscape':''}`} key={job.id} id={`video-${job.id}`}><div className="property-content-title"><h2>{label}</h2><div>{job.downloadUrl&&<a href={job.downloadUrl} download aria-label={`Télécharger ${label}`}><HomeIcon name="download" size={18}/></a>}<details className="property-content-menu"><summary aria-label={`Actions pour ${label}`}><HomeIcon name="more" size={18}/></summary><div><Link href={`/historique/${job.id}`}>Voir le suivi et les crédits</Link>{canEdit&&job.downloadUrl&&<button type="button" onClick={()=>setSocial(job)}>Publier sur mes réseaux</button>}{canEdit&&shared&&<button disabled={Boolean(busy)} type="button" onClick={()=>void sharing(job,true)}>Retirer d’Explorer</button>}</div></details></div></div>
            <p className="property-content-state"><i className={job.status==='failed'?'is-failed':!ready?'is-pending':''}/>{statusLabel(job)}<HomeIcon name={shared?'globe':'lock'} size={13}/>{shared?'Publié dans Explorer':'Privé'}</p>
            <div className={`property-video-preview${job.aspectRatio==='16:9'?' is-landscape':''}`}><img src={`/api/generations/${job.id}/source-photo`} alt="" loading="lazy" onError={event=>{event.currentTarget.style.visibility='hidden';}}/>
              {job.videoUrl?<button type="button" aria-label={`Lire ${label}`} onClick={()=>setPreview(job)}><HomeIcon name="play" size={24}/></button>:<span className="property-video-unavailable">{statusLabel(job)}</span>}
              {job.durationSeconds&&<small>{`${Math.floor(job.durationSeconds/60)}:${String(Math.round(job.durationSeconds%60)).padStart(2,'0')}`}</small>}</div>
            {canEdit&&ready&&job.videoUrl&&<Link className="property-content-edit" href={`/editeur?video=${job.id}`}><HomeIcon name="clapper" size={19}/>Modifier dans l’Éditeur</Link>}
            {canEdit&&job.status==='failed'&&job.stage==='rendering'&&job.retention==='available'&&<Link className="property-content-edit" href={`/editeur?video=${job.id}`}><HomeIcon name="clapper" size={19}/>Reprendre dans l’Éditeur</Link>}
            {canEdit&&job.downloadUrl&&!shared&&<button type="button" className="property-content-share" disabled={Boolean(busy)} onClick={()=>setConfirm(job)}><HomeIcon name="compass" size={19}/>Publier dans Explorer</button>}
            {shared&&<Link className="property-content-share" href={`/explorer/${shared.id}`}><HomeIcon name="compass" size={19}/>Voir dans Explorer</Link>}
            {!ready&&<Link className="property-content-share" href={`/historique/${job.id}`}>Voir le suivi <HomeIcon name="arrow" size={17}/></Link>}
            {job.status==='failed'&&<p className="property-content-error">{publicErrors[job.errorCode as PublicErrorCode]?.[1]??'La création a été interrompue.'}</p>}
            {canEdit&&job.retryAllowed&&<button className="property-content-edit" disabled={Boolean(busy)} type="button" onClick={()=>void retry(job)}>Relancer le démarrage</button>}
            {canEdit&&job.downloadUrl&&<button className="property-content-social" type="button" onClick={()=>setSocial(job)}><HomeIcon name="calendar" size={16}/>Publier sur mes réseaux</button>}
            {job.masterAccess==='locked'&&ready&&<Link className="property-content-share" href={`/historique/${job.id}`}>Télécharger sans filigrane</Link>}
            {canEdit&&['ready','failed'].includes(job.status)&&<ProblemReport jobId={job.id}/>}<span className="property-content-date">{date(job.createdAt)}</span>
          </article>;
        })}
        {(filter==='all'||filter==='videos')&&data.drafts.map(draft=><article className="property-content-card property-draft-card" key={draft.id}><div className="property-content-title"><h2>Brouillon</h2>{canEdit?<DraftActions agencyId={owner} draft={{id:draft.id,title:draft.title,sourceKind:'manual',locality:property.fields.locality,previewPhotoId:null,createdAt:property.updatedAt,status:'needs_input'}}/>:<HomeIcon name="pencil" size={19}/>}</div><p className="property-content-state"><i className="is-pending"/>À compléter <HomeIcon name="lock" size={13}/>Privé</p>
          <Link className="property-draft-preview" href={`/?draft=${draft.id}${draft.editor?'&fiche=1':''}`}>{property.coverUrl?<img src={property.coverUrl} alt="" loading="lazy"/>:<HomeIcon name="image" size={36}/>}<span>{draft.title}</span></Link>
          <Link className="property-content-edit" href={`/?draft=${draft.id}${draft.editor?'&fiche=1':''}`}>Continuer mon annonce <HomeIcon name="arrow" size={17}/></Link>{canEdit&&<Link className="property-content-share" href={`/editeur?draft=${draft.id}`}><HomeIcon name="clapper" size={18}/>Ouvrir dans l’Éditeur</Link>}</article>)}
        {(filter==='all'||filter==='visuals')&&Boolean(property.visualCount)&&<article className="property-content-card property-content-visual"><div className="property-content-title"><h2>Visuel prix / surface</h2><button type="button" aria-label="Télécharger le visuel prix et surface" disabled={Boolean(busy)} onClick={()=>void visual()}><HomeIcon name="download" size={18}/></button></div><p className="property-content-state"><i/>Prêt</p>
          <div className="property-price-visual"><img src={property.coverUrl!} alt="Photo du bien avec son prix et ses informations" loading="lazy"/><div><small>{property.fields.locality}</small><strong>{propertyPrice(property.fields)||property.title}</strong><span>{propertyFacts({...property.fields,locality:null})}</span></div></div>
          <button className="property-content-open" type="button" disabled={Boolean(busy)} onClick={()=>void visual()}><HomeIcon name="download" size={17}/>Télécharger le visuel</button></article>}
        {(filter==='all'||filter==='texts')&&Boolean(property.textCount)&&<article className="property-content-card property-content-text"><div className="property-content-title"><h2>Texte de publication</h2><button type="button" aria-label="Télécharger le texte de publication" onClick={()=>downloadBlob(new Blob([data.caption],{type:'text/plain;charset=utf-8'}),`bienvu-${property.reference}-publication.txt`)}><HomeIcon name="download" size={18}/></button></div><p className="property-content-state"><i/>Prêt</p><p className="property-caption">{data.caption}</p><button type="button" className="property-content-open" onClick={()=>void copy()}><HomeIcon name="copy" size={18}/>Copier</button></article>}
      </div>
      {data.nextCursor&&(filter==='all'||filter==='videos')&&<button className="property-more" type="button" disabled={Boolean(busy)} onClick={()=>void more()}>{busy==='more'?'Chargement…':'Afficher les autres vidéos'}</button>}
      {((filter==='videos'&&!data.jobs.length&&!data.drafts.length)||(filter==='visuals'&&!property.visualCount)||(filter==='texts'&&!property.textCount)||(!titleCount))&&<div className="property-empty"><h2>Aucun contenu dans cette sélection.</h2><p>{filter==='visuals'?'Ajoutez une photo et le prix ou les caractéristiques du bien pour préparer un visuel.':'Préparez votre premier contenu pour ce bien.'}</p>{canEdit&&<button type="button" className="property-primary" onClick={()=>setCreate(true)}>Créer un contenu <HomeIcon name="plus" size={18}/></button>}</div>}
    </>}
    {tab==='photos'&&<><div className="property-section-heading"><div><h2>Les photos de votre bien</h2><p>{property.photoCount} photo{property.photoCount>1?'s':''} · La première sert de couverture.</p></div>{canEdit&&<button type="button" className="property-button" disabled={Boolean(busy)} onClick={()=>void prepare('edit')}><HomeIcon name="plus" size={18}/>Ajouter ou réorganiser</button>}</div>
      <div className="property-photo-grid">{data.photos.map((photo,index)=><figure key={photo.id}><a href={photo.url} target="_blank" rel="noopener noreferrer"><img src={photo.url} alt={`Photo ${index+1} de ${property.title}`} loading="lazy"/></a><figcaption><span>{index===0?'Couverture':`Photo ${index+1}`}</span><a href={photo.url+'?download=1'} download aria-label={`Télécharger la photo ${index+1}`}><HomeIcon name="download" size={18}/></a></figcaption></figure>)}</div>{!data.photos.length&&<p className="property-notice">Ajoutez les photos du bien pour préparer vos contenus.</p>}</>}
    {tab==='information'&&<div className="property-information"><section><h2>Informations du bien</h2><dl>{[
      ['Référence',property.reference],['Type de bien',property.fields.propertyType==='apartment'?'Appartement':property.fields.propertyType==='house'?'Maison':'Autre bien'],
      ['Transaction',property.fields.transaction==='rent'?'Location':property.fields.transaction==='sale'?'Vente':'À compléter'],['Ville',property.fields.locality??'À compléter'],
      ['Surface',property.fields.area?`${property.fields.area} m²`:'Non renseignée'],['Pièces',property.fields.rooms??'Non renseignées'],['Prix',propertyPrice(property.fields)||'Non renseigné'],
      ['Charges',property.fields.charges==='included'?'Comprises':property.fields.charges==='excluded'?'Non comprises':'Non renseignées'],['Ajouté le',date(property.createdAt)],['Modifié le',date(property.updatedAt)],
    ].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section><section><h2>Description</h2><p>{property.fields.description||'Vous pouvez ajouter une description depuis « Modifier le bien ».'}</p>{canEdit&&<button className="property-button" disabled={Boolean(busy)} type="button" onClick={()=>void prepare('edit')}><HomeIcon name="pencil" size={17}/>Modifier le bien</button>}</section></div>}
    {tab==='publications'&&<><div className="property-section-heading"><div><h2>Les publications de ce bien</h2><p>Retrouvez les diffusions et les dates prévues pour vos contenus.</p></div><Link className="property-button" href="/publications"><HomeIcon name="calendar" size={18}/>Voir le calendrier</Link></div>
      {data.publications.length?<div className="property-publications">{data.publications.map(post=><article key={post.id}><div><HomeIcon name="calendar" size={24}/><h3>{date(post.scheduledAt)}</h3></div><p className="property-caption">{post.caption}</p><div className="property-publication-targets">{post.targets.map((target,index)=><span key={index}><strong>{target.platform==='instagram'?'Instagram':'Facebook'} · {target.name}</strong>{target.status==='published'?'Publié':target.status==='scheduled'?'Programmé':target.status==='processing'?'En cours':target.status==='cancelled'?'Annulé':'À vérifier'}{target.permalink&&<a href={target.permalink} target="_blank" rel="noopener noreferrer">Voir la publication <HomeIcon name="external" size={14}/></a>}</span>)}</div><Link className="property-open" href={`/publications?post=${post.id}`}>Voir le suivi <HomeIcon name="arrow" size={17}/></Link></article>)}</div>:
        <div className="property-empty"><HomeIcon name="calendar" size={34}/><h2>Votre bien attend sa première publication.</h2><p>Choisissez « Publier sur mes réseaux » sur une vidéo prête, puis une diffusion immédiate ou programmée.</p><button className="property-button" type="button" onClick={()=>{setTab('contents');setFilter('videos');}}>Choisir une vidéo <HomeIcon name="arrow" size={17}/></button></div>}</>}
    </div>
    {preview&&result?.scope===scopeKey&&<dialog ref={previewDialog} className={`property-dialog property-preview-dialog${preview.aspectRatio==='16:9'?' is-landscape':''}`} aria-label="Aperçu de la vidéo" onCancel={()=>setPreview(null)}><button className="property-dialog-close" type="button" aria-label="Fermer l’aperçu" onClick={()=>setPreview(null)}><HomeIcon name="close" size={20}/></button><h2>{property.title}</h2><video controls autoPlay playsInline preload="metadata" src={preview.videoUrl!}/></dialog>}
    {confirm&&canEdit&&<dialog ref={shareDialog} className="property-dialog" onCancel={()=>setConfirm(null)} aria-labelledby="property-share-title"><h2 id="property-share-title">Publier dans Explorer ?</h2><p>Cette vidéo et les coordonnées de votre agence deviendront visibles par tous sur BienVu. Vous pourrez retirer cette publication à tout moment.</p><div className="property-dialog-actions"><button className="property-button" type="button" onClick={()=>setConfirm(null)}>Annuler</button><button className="property-primary" type="button" onClick={()=>void sharing(confirm)}>Publier dans Explorer</button></div></dialog>}
    {create&&canEdit&&<dialog ref={createDialog} className="property-dialog" onCancel={()=>setCreate(false)} aria-labelledby="property-create-title"><button className="property-dialog-close" type="button" aria-label="Fermer" disabled={Boolean(busy)} onClick={()=>setCreate(false)}><HomeIcon name="close" size={20}/></button><h2 id="property-create-title">Un nouveau contenu pour votre bien.</h2><p>Retrouvez les photos et les informations de « {property.title} » dans l’Éditeur. Choisissez le format et ajustez votre montage avant de lancer l’export.</p><p className="property-notice">L’ouverture ne consomme aucun crédit. Le coût est affiché avant la création de la vidéo.</p><button className="property-primary" type="button" disabled={Boolean(busy)} onClick={()=>void prepare('create')}><HomeIcon name="clapper" size={20}/>{busy==='create'?'Ouverture…':'Créer une vidéo dans l’Éditeur'}</button><div className="property-create-shortcuts">{property.visualCount>0&&<button className="property-button" type="button" onClick={()=>{setCreate(false);setTab('contents');setFilter('visuals');}}>Utiliser le visuel</button>}{property.textCount>0&&<button className="property-button" type="button" onClick={()=>{setCreate(false);setTab('contents');setFilter('texts');}}>Utiliser le texte</button>}</div>{failure&&<p className="property-feedback" role="alert">{failure}</p>}</dialog>}
    {social&&canEdit&&result?.scope===scopeKey&&<SocialPublishDialog key={`${owner}:${social.id}`} job={social} onClose={()=>setSocial(null)} onPublished={()=>{setSocial(null);setRevision(n=>n+1);}}/>}
  </section>;
}
