'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {AgencyTemplate,applyAgencyTemplate,type CreationDraftView,type AgencyProfile,type VideoCustomization} from '@bienvu/contracts';
import {editorResponse} from '../lib/editor-client';
import {useAccount} from './account';
import {useGenerationStore} from './generation-store';
export type Library={projects:{id:string;name:string;archived:number}[];links:{id:string;kind:'draft'|'job';projectId:string}[];templates:{id:string;name:string;isDefault:number;template:AgencyTemplate}[];reviews:{id:string;jobId:string;status:string;expiresAt:string;approvedAt:string|null}[];comments:{reviewId:string;name:string;text:string;time:number|null;at:string}[]};
export const emptyLibrary:Library={projects:[],links:[],templates:[],reviews:[],comments:[]};
export async function studioAction(body:unknown){return editorResponse<{id?:string;url?:string}>(await fetch('/api/studio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));}
export function EditorLibrary(p:{draft:CreationDraftView;agency:AgencyProfile;save():Promise<CreationDraftView>;onApply(settings:VideoCustomization):void}){
 const [library,setLibrary]=useState(emptyLibrary),[name,setName]=useState(''),[isDefault,setDefault]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=()=>fetch('/api/studio').then(r=>editorResponse<Library>(r)).then(setLibrary);
 useEffect(()=>{void load().catch(()=>{});},[p.agency.id]);
 async function action(body:unknown){setBusy(true);setError('');try{await studioAction(body);await load();}catch(e){setError(e instanceof Error?e.message:'Modification indisponible.');}finally{setBusy(false);}}
 return <details className="editor-library"><summary>Dossier du bien et modèles d’agence</summary><div>
 <label>Dossier<select value={library.links.find(l=>l.id===p.draft.id&&l.kind==='draft')?.projectId??''} disabled={busy} onChange={e=>void action({action:'attach',projectId:e.target.value||null,kind:'draft',id:p.draft.id})}><option value="">Sans dossier</option>{library.projects.filter(v=>!v.archived).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><Link href="/projets">Gérer mes dossiers et validations →</Link>
 <label>Appliquer un modèle<select defaultValue="" disabled={busy} onChange={e=>{const template=library.templates.find(t=>t.id===e.target.value);if(template)p.onApply(applyAgencyTemplate(template.template,p.draft.photos,p.draft.data.fields,p.agency));e.target.value='';}}><option value="">Choisir un modèle…</option>{library.templates.map(v=><option key={v.id} value={v.id}>{v.name}{v.isDefault?' · par défaut':''}</option>)}</select></label>
 <label>Enregistrer ce style<input value={name} maxLength={80} onChange={e=>setName(e.target.value)} placeholder="Ex. Visite de notre agence"/></label><label className="editor-check"><input type="checkbox" checked={isDefault} onChange={e=>setDefault(e.target.checked)}/>Modèle par défaut</label>
 <button type="button" disabled={busy||!name.trim()} onClick={()=>{setBusy(true);setError('');void p.save().then(current=>studioAction({action:'template',name,draftId:current.id,version:current.version,isDefault})).then(load).catch(e=>setError(e instanceof Error?e.message:'Le modèle n’a pas été enregistré.')).finally(()=>setBusy(false));}}>Enregistrer le modèle</button>
 <p>Les modèles conservent la mise en page et les réglages. Les photos, informations du bien, musique et narration ne sont pas repris. Les textes personnalisés restent dans le modèle.</p>{error&&<p role="alert">{error}</p>}</div></details>;
}
export function WorkspaceLibrary(){
 const {me}=useAccount(),store=useGenerationStore(),[library,setLibrary]=useState(emptyLibrary),[tab,setTab]=useState('projects'),[name,setName]=useState(''),[project,setProject]=useState(''),[entity,setEntity]=useState(''),[link,setLink]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>fetch('/api/studio').then(r=>editorResponse<Library>(r)).then(setLibrary);
 useEffect(()=>{if(me)void load().catch(()=>setError('Votre bibliothèque ne peut pas être chargée.'));},[me?.agency.id]);
 async function act(body:unknown){setBusy(true);setError('');try{const result=await studioAction(body);if(result.url)setLink(new URL(result.url,location.origin).href);await load();setName('');}catch(e){setError(e instanceof Error?e.message:'Action indisponible.');}finally{setBusy(false);}}
 if(!me)return <p>Connectez-vous pour ouvrir vos dossiers. <Link href="/connexion?next=/projets">Se connecter →</Link></p>;
 return <div className="workspace-page"><header><p className="workspace-eyebrow">VOTRE AGENCE</p><h1>Vos biens, bien organisés.</h1><p>Des versions regroupées, une identité commune et une validation claire.</p></header>
 <nav className="workspace-tabs" aria-label="Bibliothèque">{[['projects','Dossiers'],['templates','Modèles'],['reviews','Validations client']].map(([id,label])=><button key={id} type="button" aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {error&&<p role="alert" className="workspace-error">{error}</p>}
 {tab==='projects'&&<><form className="workspace-form" onSubmit={e=>{e.preventDefault();void act({action:'project',name});}}><label>Nom du bien<input value={name} onChange={e=>setName(e.target.value)} maxLength={120} placeholder="Maison à Sanary-sur-Mer" required/></label><button disabled={busy||me.role==='viewer'}>Créer un dossier</button></form>
 <form className="workspace-form" onSubmit={e=>{e.preventDefault();const [kind,id]=entity.split(':');void act({action:'attach',kind,id,projectId:project});}}><label>Dossier<select required value={project} onChange={e=>setProject(e.target.value)}><option value="">Choisir…</option>{library.projects.filter(p=>!p.archived).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Création<select required value={entity} onChange={e=>setEntity(e.target.value)}><option value="">Choisir…</option>{store.drafts.map(d=><option key={d.id} value={'draft:'+d.id}>{d.title??'Brouillon'}</option>)}{store.jobs.map(j=><option key={j.id} value={'job:'+j.id}>{j.title} · {j.status}</option>)}</select></label><button disabled={busy||me.role==='viewer'}>Classer</button></form>
 <div className="workspace-cards">{library.projects.map(p=><section key={p.id}><h2>{p.name}</h2><span>{p.archived?'Archivé':'Dossier actif'}</span>{library.links.filter(l=>l.projectId===p.id).map(l=><Link key={l.kind+l.id} href={l.kind==='draft'?'/editeur?draft='+l.id:'/historique/'+l.id}>{l.kind==='draft'?store.drafts.find(d=>d.id===l.id)?.title??'Brouillon':store.jobs.find(j=>j.id===l.id)?.title??'Vidéo'} →</Link>)}<button disabled={busy||me.role==='viewer'} type="button" onClick={()=>void act({action:'archive',id:p.id,archived:!p.archived})}>{p.archived?'Rouvrir':'Archiver'}</button></section>)}</div>{!library.projects.length&&<p>Créez un dossier pour retrouver les brouillons et exports d’un même bien.</p>}</>}
 {tab==='templates'&&<><p>Enregistrez un modèle depuis l’Éditeur. Le modèle par défaut s’applique à l’ouverture d’un nouveau projet dans l’Éditeur.</p><div className="workspace-cards">{library.templates.map(t=><section key={t.id}><h2>{t.name}</h2><p>{t.isDefault?'Modèle par défaut':'Modèle d’agence'} · {t.template.document.aspectRatio} · {t.template.document.durationSeconds} s</p><button type="button" disabled={busy||me.role==='viewer'} onClick={()=>void act({action:'delete-template',id:t.id})}>Supprimer ce modèle</button></section>)}</div></>}
 {tab==='reviews'&&<><form className="workspace-form" onSubmit={e=>{e.preventDefault();void act({action:'review',jobId:entity});}}><label>Vidéo à faire valider<select required value={entity} onChange={e=>setEntity(e.target.value)}><option value="">Choisir…</option>{store.jobs.filter(j=>j.status==='ready'&&j.masterAccess==='unlocked'&&j.retention==='available').map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></label><button disabled={busy||me.role==='viewer'}>Créer un lien privé</button></form>
 {link&&<div className="workspace-share"><label>Lien à transmettre<input readOnly value={link} onFocus={e=>e.target.select()}/></label><button type="button" onClick={()=>void navigator.clipboard.writeText(link).catch(()=>setError('Sélectionnez le lien pour le copier.'))}>Copier</button><a href={link} target="_blank" rel="noreferrer">Ouvrir</a></div>}
 <div className="workspace-cards">{library.reviews.map(r=><section key={r.id}><h2>{store.jobs.find(j=>j.id===r.jobId)?.title??'Version vidéo'}</h2><p>{r.status==='approved'?'Validée':r.status==='revoked'?'Lien révoqué':r.status==='commented'?'Commentaires reçus':'En attente'} · expire le {new Date(r.expiresAt).toLocaleDateString('fr-FR')}</p>{library.comments.filter(c=>c.reviewId===r.id).map((c,i)=><blockquote key={i}><strong>{c.name}{c.time!==null?` · ${c.time.toFixed(1)} s`:''}</strong><p>{c.text}</p></blockquote>)}<Link href={'/historique/'+r.jobId}>Voir la version →</Link><button disabled={busy||me.role==='viewer'||r.status==='revoked'} type="button" onClick={()=>void act({action:'revoke-review',id:r.id})}>Révoquer le lien</button></section>)}</div><p>Chaque validation porte sur une version précise. Un nouvel export nécessite une nouvelle validation.</p></>}
 </div>;
}
